### ISSUE TITLE
tsc_wrapped cannot find tslib when importHelpers is set to true

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1023]
I will look more into this soon. From first glance it looks like Typescript cannot resolve where 'tslib' is even if it is part of the `@//:node_modules` filegroup.

The error reported is:

```
ERROR: /private/var/tmp/_bazel_greg/34cb2c27ba201fc3e02405892697c98f/external/rxjs/BUILD.bazel:22:1: Compiling TypeScript (devmode) @rxjs//:rxjs failed (Exit 1)
external/rxjs/index.ts:73:1 - error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
```

**Comment by ashi009** [comment]
I also run into this issue. However, I can't reproduce it consistently.  By simply changing the content of the source file and recompile, the issue will go away automatically.

I think this might have something to do with the worker's resolver cache?

**Comment by ashi009** [comment]
Ah, it's not resolver cache, but the program cache. As the typescript compiler will try to insert a synthetic import to the AST based on the `importHelpers` option. So if the cached AST was generated with `importHelpers` disabled, and then being consumed in a later task that has `importHelpers` enabled, TS2354 will be thrown. 

I believe this can be fixed by making the program cache aware of the changes made to the tsconfig.
