### ISSUE TITLE
IDE support in large monorepo

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1047]
When a source tree is really large, editors can't load the entire repository.

Users should be able to open a subdirectory of the repository, without losing features like type-checking and auto-completion referencing symbols declared outside that subdirectory.

In other languages, bazel supports it with a plugin:
https://blog.bazel.build/2016/06/10/ide-support.html

We might want something similar to create a tsconfig.json section that gives the needed pathMappings to teach typescript how to find the `bazel-out/.../path/to/dependency/api.d.ts` files needed.

**Comment by ribrdb** [comment]
We're starting to run into this issue.
I know ts_library is creating a tsconfig for each ts_library.
I wonder if there's some way we could get tsserver to use these smaller typescript projects instead of trying to load the whole monorepo into memory.

**Comment by DavidANeil** [comment]
For what its worth we used to have our repo split into ~30 projects with their own `tsconfig.json`, and TSServer would consume a lot of memory because it didn't share state between the dependent projects well (or at all?).

Things might have changed since then (composite projects being a big one), but I would recommend trying it out with manually placed `tsconfig.json`s before trying to integrate with Bazel.
