### ISSUE TITLE
TS moduleResolution is slow when tsconfig.json is in the root dir

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1049]
Because we set rootPath = project_dir and then TS reads into the bazel-projectname symlink recursively and spends 20s stat'ting files.

Workaround is to include in `.bazelrc`:
```
build --symlink_prefix=/
```

thanks for debugging it, @hansl

**Comment by KrauseStefan** [comment]
Just a note this causes a similar issue for other tools, our biggest issue is with Teamcity recursively scanning for build artifacts or JUnit reports.
Currently our workaround is setting
``` 
build --symlink_prefix=../.bazel_tmp
```
This breaks the recursive folder structure
It does not work for us to use
```
build --symlink_prefix=/
```
since this also removes the `bazel-out` folder

**Comment by joeljeske** [comment]
@alexeagle is this issue regarding TSServer during development or at a build time?
