### ISSUE TITLE
Add angular universal (SSR and PWA) to the example

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1126]
Probably for @Toxicable to do sometime.

**Comment by Toxicable** [comment]
Ill take a look at writing a rule which calls the @angular/pwa cli manifest generation tool.
Since that should be low cost to put in.

Then(or in parallel) I can take a look at doing some universal stuff aswell

**Comment by Toxicable** [comment]
I did a small start on running universal under bazel but ran into a few issues. 
Ill revisit when we support v9 since that resolve a few of them

**Comment by marcus-sa** [comment]
Anything that I can help with regarding PWA support?

**Comment by alexeagle** [comment]
hey @marcus-sa can you get something working under https://github.com/bazelbuild/rules_nodejs/tree/master/examples/angular ? you can just `cd` into that directory and hack. If you get something working we can merge it to the example

**Comment by marcus-sa** [comment]
@alexeagle I've just fiddled around with it and IMO it would be better to create a Bazel definition for it called `ng_service_worker` in the `@angular/bazel` package as there would be a lot of redundant config/code needed for end users to be able to use it properly, since they'd need to copy the required files such as `ngsw-worker.js`, `safety-worker.js` and `worker-basic.min.js`.
This is done automatically by the Angular CLI as seen here:
https://github.com/angular/angular-cli/blob/da6d74a86e208cc5dc0a83718fb9122ca31addd4/packages/angular_devkit/build_angular/src/browser/index.ts#L682

**Comment by flolu** [comment]
Are there any updates on Bazel with Angular Universal? This is the last step for my migration to Bazel, and I really need it.
If there is no progress, then how could it be implemented?
