### ISSUE TITLE
Change default ts_library output to .js

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1154]
Currently it is .d.ts

**Comment by alexeagle** [comment]
Note you can already work around this with a macro like

```
def ts_js_library(name, **kwargs):
 ts_library(
        name = "_%s_compile" % name,
        **kwargs
    )

    native.filegroup(
        name = name,
        srcs = ["_%s_compile" % name],
        output_group = "es5_sources",
    )
```

**Comment by alexeagle** [comment]
I documented both the filegroup approach to get the .js files and the use of plain `tsc`
https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/docs/install.md

so this is no longer needed for 1.0

**Comment by kylecordes** [comment]
Looking back at this issue:

I understand *why* the default output is the d.ts, and it's quite nice to see that reasoning documented.

But: it is still a surprising speedbump during adoption.

I wonder if there is any precedent among other, longer-used Bazel rulesets for the default output of a compiler being a representation of the API of the executable output, rather than the output itself. Something to point at as "the Bazel way of doing things".

**Comment by marcus-sa** [comment]
What's the reason behind not allowing `.js` files as sources for `ts_library`?
