### ISSUE TITLE
ts_library: Allow disabling of compiler option overrides.

### ISSUE THREAD

**Issue by WearyMonkey** [bazelbuild/rules_nodejs#1175]
# 🚀 feature request

### Relevant Rules

`ts_library`

### Description

The `ts_library` has hardcoded compilerOption overrides. Not all projects will want to use the same options as Google. E.g. the `target`, `baseUrl` need to be changed for our project, and I can imagine wanting to change many other options.

relevant code:
https://github.com/bazelbuild/rules_typescript/blob/4a399172f320f396355e7106e2a2372099eb75b4/internal/common/tsconfig.bzl#L188

### Describe the solution you'd like

A rule argument that allows disabling the compiler option overrides.

### Describe alternatives you've considered

I can't think of many. We could provide our own `tsc_wrapper` compiler that would remove the `ts_library` rules.

**Comment by Toxicable** [comment]
Some of these options, such as `baseUrl` and `target` are required for bazel to work correctly.
Without them set the downstream targets may not work, or it may not even compile in the first place.

However, some of these, such as target could be more editable with some redesign, check the other issues concerning that specifically `target`.

**Comment by WearyMonkey** [comment]
@Toxicable thanks for your fast reply!

> Some of these options, such as baseUrl and target are required for bazel to work correctly.

Our project has `baseUrl` set to `./src`, but the `ts_library` rule overrides it back to the project root (workspace). That breaks are imports form `./src`.

What is the recommended approach to solving this problem?

**Comment by alexeagle** [comment]
Currently our TypeScript support is a bit opinionated.

Really the only settings we absolutely need to control are related to paths of inputs and outputs, since Bazel prescribes where these should go.

`baseUrl` does interact with these. When you use path-mapping (giving a short import name for a first-party package in your monorepo) we need to know how to resolve it. So if your `my-lib` lives in `//packages/my-lib` we need to write path mappings including how TS can resolve that library.

In theory you could choose that your TS code is rooted in a subdirectory of your monorepo, but then what if you have multiple such roots, and a ts_library has a dep on more than one of them? Then there is no single setting of `baseUrl` that will work for that compilation. So I think it would be hard to give you control of that option while still keeping builds working.

In fact, you could probably reproduce the same issue without Bazel, using TypeScript's "composite projects" feature. To make a setup with multiple roots work, you'd probably break things if you had pathmapping with multiple baseUrls required.

We could give this some more thought but for now I think we need to control `baseUrl`.

You could make it work with one of:
- change your TS imports to be relative
- add the `wksp/src/` prefix on the front of your imports to match the layout of your repo
- add a pathMapping for each subdirectory of `src`, so if you're trying to `import 'foo'` and you have `my_repo/src/foo` then you need a `ts_library` in that directory with `module_name="foo"`

Or another option would be to have the WORKSPACE file in the src directory, but this will get complicated if you also want bazel to build things outside src, you'll need multiple workspaces.

**Comment by alexeagle** [comment]
Here's a general answer: you could use vanilla `tsc` rather than `ts_library`. It has some limitations: it doesn't keep a warm compiler running, so it can be slower, and you can't use it in the `deps` of a ts_library or ng_module. It's not the way we do it at Google but you can control TypeScript as much as you like this way.

It would look something like this:
```python
load("@npm//typescript:index.bzl", "tsc")
srcs = glob(["*.ts"])

tsc(
        name = "compile",
        data = srcs + deps,
        outs = [s.replace(".ts", ext) for ext in [".js", ".d.ts"] for s in srcs],
        args = [
            "--outDir",
            "$@",
            "--lib",
            "es2017,dom",
            "--downlevelIteration",
            "--declaration",
        ] + [
            "$(location %s)" % s
            for s in srcs
        ],
    )

```

**Comment by booninite** [comment]
Also running into this problem because some open source projects (in this case, Hexo -- https://hexo.io) chokes on the module if the file ends with an inlineSource without a new line.  I have opened an issue against Hexo, but it would be useful to have control over aspects of `tsconfig.json` that don't seem to be required for Bazel + TypeScript to happily work together.
