### ISSUE TITLE
ng Build failed

### ISSUE THREAD

**Issue by salim-boudriiya** [bazelbuild/rules_nodejs#1191]
Hi,

I am trying to build the angular example, but I have the following error.

ESPC006863:angular smba$ ng build
ERROR: error loading package '': Unable to load file '@build_bazel_rules_nodejs//:index.bzl': file doesn't exist
ERROR: error loading package '': Unable to load file '@build_bazel_rules_nodejs//:index.bzl': file doesn't exist
INFO: Elapsed time: 0.068s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

Can you help me please.

regards

**Comment by gregmagolan** [comment]
Oh that is interesting.

What is needed to get the example building is to go back to the commit of the last rules_nodejs release which was https://github.com/bazelbuild/rules_nodejs/releases/tag/0.37.1. The commit is https://github.com/bazelbuild/rules_nodejs/commit/a4bebf2d2da13d93e08e75bd720e2dff8a3a3afe.

This is because the example references that version in its WORKSPACE file and there has been some breaking refactoring since then including a rename of `@build_bazel_rules_nodejs//:defs.bzl` => `@build_bazel_rules_nodejs//:index.bzl`. We're adding in these breaking changes now before we hit 1.0 but after 1.0 this should not be an issue typically.

**Comment by alexeagle** [comment]
Yeah we are always in a place where the examples can be broken until the next release.

Should we try to get ppl browsing the sources on the latest tag rather than on HEAD?

**Comment by gregmagolan** [comment]
Yes. That's a good idea I think as even the HEAD docs can be misleading as they may apply to the next release which hasn't happened yet: https://github.com/bazelbuild/rules_nodejs/pull/1189

**Comment by alexeagle** [comment]
For docs we already had a good answer, which is that it's generated during the release process so I made a mistake applying a refactoring to the skydoc output. The Docs folder should always represent the latest release, not head

**Comment by salim-boudriiya** [comment]
Good morning,

Thank you very much for your clarification, I will return to the version you tell me and I will try again.

Cordially.

**Comment by salim-boudriiya** [comment]
Hi @alexeagle and @gregmagolan ,

I just launched with the version that @gregmagolan has told me, and it worked correctly.

Best regards

**Comment by salim-boudriiya** [comment]
INFO: Analyzed target //src:prodapp (526 packages loaded, 28757 targets configured).
INFO: Found 1 target...
Target //src:prodapp up-to-date:
  dist/bin/src/prodapp
INFO: Elapsed time: 229.599s, Critical Path: 121.22s
INFO: 26 processes: 10 darwin-sandbox, 1 local, 15 worker.
INFO: Build completed successfully, 13149 total actions

**Comment by gregmagolan** [comment]
🎉
