### ISSUE TITLE
Can't get es6 output from ts_library for nodejs_binary

### ISSUE THREAD

**Issue by JaredNeil** [bazelbuild/rules_nodejs#122]
I have a Typescript program that uses es6 features that I'd like to use as a `nodejs_binary`, but the `nodejs_binary` rule doesn't have an option to tell the `ts_library` to compile to the es6 target, so I get errors when tsc tries to compile to es5.

I also tried using the `es6_consumer` rule (`nodejs_binary` > `es6_consumer` > `ts_library`), but no luck with that either.

Is there a way to do this that I'm missing, or is this a feature that needs to be added?

**Comment by alexeagle** [comment]
@hansl ran into the same thing (wanted to subclass `Error`)

No, currently ts_library has only two output flavors: devmode and prodmode. since nodejs needs commonjs, we can't feed it the prodmode output that has ESModules. So the devmode is the only output that can be loaded in node, and devmode downlevels so it targets a wider range of browsers.

That said, I think the fix is to make devmode use UMD+ES2015 syntax *everywhere*, once we are confident that every development runtime including nodejs and browsers works with this.

**Comment by alexeagle** [comment]
Oh, also could you give some hints what you want to do, that you can't do today? What es2015 feature do you need in nodejs that typescript downlevels away?

**Comment by JaredNeil** [comment]
So after playing with this for the past few days (mostly yesterday) I think I figured out what was going wrong.
I have an existing project that I just run `tsc` to compile and `node out/my_script.js` to run. My `tscongif.json` sets the target as `es6`, this implicitly sets the `lib` option to `["dom", "dom.iterable", "es6", "scripthost"]` (https://www.typescriptlang.org/docs/handbook/compiler-options.html). When bazel overwrites the `target` to `es5` those libraries are no longer included, and the compilation fails (specifically, I was using `string.startsWith`). Explicitly setting the `lib` option allows the compilation to succeed.
I believe the fix would be to also set the `lib` property to the correct defaults if the `target` is being downgraded. If that sounds like a reasonable thing to do, I'd be happy to put together a PR for rules_typescript.

That doesn't fix everything, however, because I still get a runtime error about `__spread` not being defined. So I have to change the `noEmitHelpers` option from true to false. Maybe this option also needs changed if the target is being changed?

All of this comes down to rules_typescript changing the tsconfig.
If I just comment out these two sections of rules_typescript (https://github.com/bazelbuild/rules_typescript/blob/master/internal/common/tsconfig.bzl#L130 and https://github.com/bazelbuild/rules_typescript/blob/master/internal/build_defs.bzl#L112-L118), then `bazel run :my_script_target` works as expected because I get output that matches what I get when running `tsc`. I guess I'm not sure why the ts_library rule needs to change the tsconfig at all. It seems a lot simpler to me to just let the person writing the code to also write the config. This is probably just because I don't know the reasons why. Is there anywhere I can find the reasons behind this "consumer chooses config" paradigm?

After this further investigation, I've realized this issue probably should have been filed against rules_typescript.

**Comment by alexeagle** [comment]
You can set the `lib` option in your own tsconfig. And you should include `tslib` at runtime to get the helpers.

The reason for controlling the configuration is because you might need *both* configurations. eg. `ts_devserver` wants UMD output that's quick to concat, while `rollup_bundle` wants ES2015 modules.

**Comment by alexeagle** [comment]
Any remaining questions here? Is there still an issue for me to fix?
Closing pre-emptively but please comment if I missed something.

**Comment by booninite** [comment]
Since the linked code sets the `target` value on the `tsconfig.json`, is there any way to actually produce an ES6 module using `ts_library`? It seems like no -- but want to verify my understanding is correct.
