### ISSUE TITLE
npm_install & yarn_install does not seem to honor .npmrc and .yarnrc in data attribute

### ISSUE THREAD

**Issue by yoonjesung** [bazelbuild/rules_nodejs#1311]
### Description

Using rules_nodejs v0.39.0 and bazel v0.29.1

When supplying a data target to a .npmrc or .yarnrc file, the configurations are not being honored by `yarn_install`/`npm_install`

### Minimal steps to reproduce

Tested with setting the `registry` config, but the resulting lock files do not using the appropriate registry.

### Additional information

When using `symlink_node_modules = True`, however, `yarn_install` and `npm_install` will appropriately use the .yarnrc/.npmrc files respectively in the location of the `package.json` dir.

**Comment by alexeagle** [comment]
Do you pass the `.rc` file to the `data` attribute of the `yarn_install`/`npm_install` rule?

**Comment by igilham** [comment]
That's one way of doing in, but I wonder if there's a broader need for more consistency. The typescript config file is passed by exporting with a magic filename it in a separate rule, [for example](https://github.com/igilham/bazel-example/blob/master/BUILD.bazel).

I agree that we should be able to configure npm/yarn, but I'd like config to work the same for different tools where possible. I prefer explicit config over magic files, but am not very opinionated on the approach as long as the documentation is clear.

**Comment by yoonjesung** [comment]
@alexeagle yes I passed the respective `.rc` file into the data param but did not update the registry.

**Comment by ViceIce** [comment]
I'm trying to use angular with bazel and a private npm repository (authtoken added to `~/.npmrc`).

* when i run `yarn` from local directory, every thing is fine and yarn finds the auth token
* when i run `ng build` which call `yarn_install` bazel rule i got `401 Unauthorized` for my private packages.

So looks like the `.rc` files from user home are ignored?

**Comment by hristozov** [comment]
As a workaround, for npm the config file can be passed by passing `userconfig` with the path of the copied data file:
```python
npm_install(
    name = "npm-some-target",
    args = ["--userconfig some-target/.npmrc"],
    data = ["//some-target:.npmrc"],
    package_json = "//some-target:package.json",
    package_lock_json = "//some-target:package-lock.json",
    symlink_node_modules = False,
)
```
Of course, this is actually a hack as it depends on [the way data files are placed in the root](https://github.com/bazelbuild/rules_nodejs/blob/26f669836204bcb9de0ecfb88c129d582bf427a5/internal/npm_install/npm_install.bzl#L178-L187).

**Comment by gregmagolan** [comment]
When `symlink_node_modules = True`, you have to manually add all of the inputs to `yarn_install` and `npm_install` to the `data` attribute. #1866 improves the docstring for `data` and also includes a fix so that Bazel will evaluate all of the labels in `data` to ensure they are valid files. It is possible that the label you supplied was incorrect (such as `//.yarnrc` instead of the correct `//: .yarnrc`) as it is not currently checked by Bazel.

**Comment by gregmagolan** [comment]
> As a workaround, for npm the config file can be passed by passing `userconfig` with the path of the copied data file:
> 
> 
> ```python
> npm_install(
>     name = "npm-some-target",
>     args = ["--userconfig some-target/.npmrc"],
>     data = ["//some-target:.npmrc"],
>     package_json = "//some-target:package.json",
>     package_lock_json = "//some-target:package-lock.json",
>     symlink_node_modules = False,
> )
> ```
> 
> Of course, this is actually a hack as it depends on [the way data files are placed in the root](https://github.com/bazelbuild/rules_nodejs/blob/26f669836204bcb9de0ecfb88c129d582bf427a5/internal/npm_install/npm_install.bzl#L178-L187).

Yes, that looks correct as the files in `data` are copied to the external repository with their full package path. It seems like the correct thing to do in this case is to strip the package path of the `package.json` file from the `data` files so the behavior when `symlink_node_modules` is `True` or `False` is the same. However, this would mean that any `data` files outside of the `package.json` package and sub-packages could not be copied over.

**Comment by DavidANeil** [comment]
@gregmagolan I believe that is what https://github.com/bazelbuild/rules_nodejs/pull/765 was trying to do

**Comment by gregmagolan** [comment]
> @gregmagolan I believe that is what #765 was trying to do

Thanks for digging that up. I'll bring it up in the rules_nodejs sync meeting today. It seems like that is more correct but we'd have to somehow handle `data` files that are outside of the package.json package & sub-packages. It seems like this will just be a limitation when `symlink_node_modules = False`. Open to suggestions.

**Comment by gregmagolan** [comment]
Oh. I think I understand the principled fix. The package.json & yarn.lock files should themselves be put into the external repo with their package paths in place. So a package.json at `/path/to/package.json` would end up at `@npm//:path/to/package.json` in the external repository and that is where yarn/npm should run when symlink_node_modules is False. That would layout node_modules at `@npm//:path/to/node_modules`. This would be a breaking change for existing `@npm//:node_modules/...` labels but we can do that for 2.0.

We may also want to put everything in some `internal` folder in `@npm` so that workspace packages names don't conflict with npm package names so you would end end up with `/path/to/package.json` be put in `@npm//:internal/path/to/package.json` and the node_modules would be layed out at `@npm//:internal/path/to/node_modules`

**Comment by Toxaris** [comment]
FYI for `yarn_install`, the following seems to work:

```
yarn_install(
    name = "npm",
    args = ["--no-default-rc", "--use-yarnrc=some/folder/.yarnrc"],
    data = ["//some/folder:.yarnrc"],
    package_json = "//some/folder:package.json",
    yarn_lock = "//some/folder:yarn.lock",
    symlink_node_modules = False,
)
```

I found the CLI options in https://github.com/yarnpkg/yarn/blob/6db39cf0ff684ce4e7de29669046afb8103fce3d/src/cli/index.js#L73-L79.
