### ISSUE TITLE
Accedental dependencies in generated rules

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_nodejs#1333]
# 🐞 bug report

### Affected Rule
All auto generated rules

### Description
All external dependencies are pulled in at runtime when executing any auto generated rules.

## 🔬 Minimal Reproduction
I've got a reproduction in this repo: https://github.com/purkhusid/rules_nodejs_dep_repro

In this repro I've got a simple webpack bundle where the application code imports Lodash and uses it.
I also omit Lodash from the `data` attribute in the `BUILD.bazel` file and yet the webpack bundle succeeds.
I was expecting the build to fail since I did not declare the dependency in the target.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Mojave
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.29.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Sep 10 13:47:42 2019 (1568123262)
Build timestamp: 1568123262
Build timestamp as int: 1568123262
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
26c39450ce2d825abee5583a43733863098ed29d3cbaebf084ebaca59a21a1c8
  </code>
</pre>

**Comment by soldair** [comment]
related to conversation in the bazel slack around here https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1572884573348800

**Comment by purkhusid** [comment]
Just wanted to update that this is the case for all files, not only for npm dependencies. I can skip all my `.js` files in my webpack target and the bundle will still succeed since it seems like it's going outside it's sandbox.

@soldair @alexeagle Will #1332 fix this?

**Comment by alexeagle** [comment]
This is a general Bazel limitation of what sandboxing can achieve. If you use the strongest sandbox (Remote Build Execution or remote-on-local like https://docs.bazel.build/versions/master/remote-execution-sandbox.html ) I think you'll see that the action only sees the files you declare as dependencies.

Any program (not just nodejs) can look around the disk. In this case the program is our linker which symlinks all the node_modules present. We can probably make this tighter but I'd still advise having some CI testing with a stronger sandbox if you want to enforce that your dependencies are fully specified, since you could easily introduce your own build step (like with a genrule) that isn't hermetic (reads files not declared as inputs)

**Comment by purkhusid** [comment]
@alexeagle Alrighty, but rules_nodejs should still aim to create hermetic rules that work in the default sandbox, right? What is standing in the way of linking only files that are declared in the rule inputs?

**Comment by kylecordes** [comment]
Is it be completely beyond hope that a future version might do filesystem level sandboxing by default?

I imagine the quality boost from rules developed in an environment where the sandbox is secure, and then only trusted for direct (and somewhat more performance) disk access after thusly proven.

**Comment by purkhusid** [comment]
This seems to fixed in the latest version of rules_nodejs.
