### ISSUE TITLE
Cannot extend React Webpack example

### ISSUE THREAD

**Issue by sahilprasad** [bazelbuild/rules_nodejs#1339]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: webpack?

### Is this a regression?

 No.

### Description

 I'm trying to extend the current React + Webpack example by adding a simple `App.tsx` component. The component isn't being resolved.

## 🔬 Minimal Reproduction

<https://github.com/sahilprasad/rules_nodejs/commit/eab7f191c12753892531711b151baf2e31d00de2>

## 🔥 Exception or Error

<pre><code>

 
Module not found: Error: Can't resolve './App' in '/home/sahil/.cache/bazel/_bazel_sahil/9c2ef9c374524a75985c0d19162986b0/execroot/react_webpack/bazel-out/k8-fastbuild/bin`.

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    Ubuntu 19.04
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.29.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Sep 10 13:44:39 2019 (1568123079)
Build timestamp: 1568123079
Build timestamp as int: 1568123079
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
  Off of master.
  </code>
</pre>

**Comment by alexeagle** [comment]
It's because your "compile" action doesn't declare that "App.jsx" is an output, so that file is not passed by bazel to downstream rules that depend on it.

Add "App.jsx" here: https://github.com/sahilprasad/rules_nodejs/commit/eab7f191c12753892531711b151baf2e31d00de2#diff-e2a4f9b4277fb8d86216b6359420fd56R18

(Or use a list comprehension so the output list is derived from the input list)
