### ISSUE TITLE
Allow custom rules to generate stardoc 

### ISSUE THREAD

**Issue by clintharrison** [bazelbuild/rules_nodejs#1348]
Custom rules that `load()` providers/etc. from `rules_nodejs` cannot generate stardoc documentation.

`bzl_library` from skylib is mocked out to `filegroup`, which means your own rules have missing dependencies from Stardoc's perspective.
You can try creating your own `bzl_library` with those filegroups, but you end up needing to reference filegroups in `//internal` which don't have visibility outside of this workspace.

**Comment by alexeagle** [comment]
Maybe one way to solve this is to stop mocking out the skylib dependency and make users add a WORKSPACE dependency so that bzl_library load statements work for everyone.

A bit more complex would be a "lite" distro with minimal deps and a heavier distro. A lot more complex would be for you to switch to getting rules_nodejs from sources rather than our tgz distro

**Comment by alexeagle** [comment]
There's another possibility I didn't think of in the last comment - you could use a local patch to restore the original stardoc load statements.

**Comment by mattem** [comment]
I made this patch for 1.6.1 that is used in my orgs repo to allow Stardoc generation where rules_nodejs is loaded, if you did want to go the patch route.

**Comment by alexeagle** [comment]
I think we may already be in a state where you can use rules_nodejs from source rather than the distro artifacts. That gives another tidy answer to this, just switch to sources and then all our dev dependencies will be exposed.

**Comment by mattem** [comment]
Added example in #2056 for using rules_nodejs from source and generating docs with stardoc
