### ISSUE TITLE
Allow users to set output directory for each `output_group` in `ts_library

### ISSUE THREAD

**Issue by fredrikredflag** [bazelbuild/rules_nodejs#1356]
# 🚀 feature request

Allow users to set output directory for each `output_group` in `ts_library`. It would help with organising code when publishing npm packages. 

Instead of having `index.js` (es5) and  `index.mjs` (es2015) side by side. 

### Relevant Rules

`ts_library`

### Description

When publishing a npm package with multiple target (es2015, es5, esm2015 etc), it would be nice to be able to organising the code to have each target in a separate folder. Like @angular's npm packages. 

### Describe the solution you'd like

It would be nice to have something like:

```typescript
ts_library(
    name = "service-api",
    srcs = glob([
        "src/**/*.ts",
    ]) + ["index.ts"],
    module_name = "@red/tservice-api",
    tags = ["library"],
    deps = [
        "@npm//@types",
    ],
    output_groups = {
        "es5_sources": "es5/"
        "es6_sources": "es2015/"
    }
)
```

### Describe alternatives you've considered

I've tried a few different solutions. 
1. Have a node script that rearrange the code after the npm packages is built, but before it's published. I think this is how @angular does it. 
2. A genrule that copies file and renames them 

Both solutions doesn't feel scaleable, it would be nice to be able to easy mimic @angular's npm structure.

**Comment by alexeagle** [comment]
It's totally reasonable for the output structure to differ from the sources structure. However under Bazel this is always done in a terminal rule in the graph (a '*_package` rule). The reason is that any other intermediate steps in the graph should see sources layed out like the input tree, so that the rules are composable independent from each other (if `ts_library `changed in this way then lots of downstream rules might need to be aware of the changed output structure)

Take a look at the `ng_package` rule in Angular, maybe this already suits your needs? otherwise I think you want to write a similar rule.

**Comment by fredrikredflag** [comment]
@alexeagle Thanks for your input. I tried `ng_package` rule, should have thought about it earlier, and it works fine! Needed to tweak it a bit. 

Didn't realize that on can load macro like `load("@build_bazel_rules_nodejs//internal/npm_package:npm_package.bzl", ...)`.

**Comment by fredrikredflag** [comment]
Maybe a simplistic example for changing the output structure from `ts_library` would be nice to have under `examples`? I would be happy to write one if it doesn't feel to out of scope?
