### ISSUE TITLE
Performance: Link node_modules using Runfiles symlinks

### ISSUE THREAD

**Issue by mrmeku** [bazelbuild/rules_nodejs#1489]
See https://docs.bazel.build/versions/master/skylark/rules.html#runfiles-symlinks

Normally, the relative path of a file in the runfiles tree is the same as the relative path of that file in the source tree or generated output tree. If these need to be different for some reason, you can specify the root_symlinks or symlinks arguments. The root_symlinks is a dictionary mapping paths to files, where the paths are relative to the root of the runfiles directory.

If we were to link the node_modules directory using this bazel semantic, we could skip running the linker entirely since Bazel will have essentially done the work for us. Bazel is already doing this work when creating the run files directory, it unfortunately just links those files into `runfiles/npm/external` (which requires us to run the linker program to move the files to where they need to be)

**Comment by alexeagle** [comment]
We still need the linker for the npm_package_bin case (a program run as a tool in the execroot to transform inputs to outputs under bazel build - no runfiles is set up for that)

This does look like an interesting refactor for the bazel run / bazel test case, we might be able to skip the linker for nodejs_binary/nodejs_test if we can configure it here. OTOH it means having two different ways to do the same mapping, since npm_package_bin would still need the linker as a standalone program.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
