### ISSUE TITLE
performance: poor cache performance

### ISSUE THREAD

**Issue by Toxicable** [bazelbuild/rules_nodejs#1501]
# 🐞 bug report

### Affected Rule
`ts_library` and `ng_module`
Although there should a be issue on the angular tracker for `ng_module`  - it's possible they're related.

### Is this a regression?
unknown

### Description
Tracking caching issues with `ts_library` and `ng_module`, 
When making a change you should expect to get a cache hit, it's common to instead see a miss.
@jbedard and @gregmagolan  might have a better description here.

(Sorry not publically accessible)
https://bazelbuild.slack.com/archives/GMADCN4ES/p1577237625018000

**Comment by jbedard** [comment]
FYI I think my issues are caused by https://github.com/angular/angular/issues/34635 which can occur with anything depending on an `@angular/*` package which `ngcc` runs on. This won't happen when `node_modules` is cached which is why many people haven't seen such an issue, especially locally (unlike CI which might not cache `node_modules`).

**Comment by jbedard** [comment]
Can also occur due to https://github.com/angular/angular/issues/35180

**Comment by jbedard** [comment]
https://github.com/angular/angular/issues/35180 has been merged and should be in the next angular release. That's at least one case of this occurring for me.

@Toxicable did you ever notice a decrease in this?

**Comment by Toxicable** [comment]
I'm not tracking any specific issues at the moment.
I have noticed some odd/poor cache issues, but I think it's largely due to our repository setup at the moment.
I think we'd be best to close this one , can always make a new one if we find any other specific issues
