### ISSUE TITLE
rollup_bundle not bundling typescript correctly.

### ISSUE THREAD

**Issue by gluaxspeed** [bazelbuild/rules_nodejs#1545]
# 🐞 bug report

### Affected Rule
ts_library()?
rollup_bundle()

### Is this a regression?
Not sure, I haven't used it before this version.

### Description
Having a internal ts_library dependency for another ts_library then calling rollup_bundle for it does not bundle correctly.

I also fail to see the output of the testlib bundled anywhere.

## 🔬 Minimal Reproduction
With a directory setup of:

- project/
  - package.json
  - tsconfig.json
  - WORKSPACE
  - typescript/
    - testlib
      - BUILD
      - index.ts
    - app
      - BUILD
      - index.ts
      - index.html
      - style.css

project/typescript/teslib/BUILD
```bazel
package(default_visibility = ["//visibility:public"])
load("@npm_bazel_typescript//:index.bzl", "ts_devserver", "ts_library")

ts_library(
    name = "testlib",
    srcs = glob(["*.ts"]),
    module_name = "@testlib"
)
```
project/typescript/teslib/index.ts

```typescript
export class Person {
    private _name: string;

    constructor(name: string) {
        this._name = name;
    }

    greet(): string {
        return "Hello, " + this._name; 
    }
}```

project/typescript/app/BUILD
```bazel
load("@npm_bazel_typescript//:index.bzl", "ts_library", "ts_devserver")
load("@npm_bazel_rollup//:index.bzl", "rollup_bundle")

ts_library(
    name = "app",
    srcs = [
        "index.ts",
    ],
    deps = [
        "//typescript/testlib"
    ]
)

ts_devserver(
    name= "devserver",
    static_files = [
        "bundle.js",
        "index.html",
        "style.css",
    ],
)    

rollup_bundle(
    name = "bundle",
    entry_point = "index.ts",
    deps = [
        ":app",
    ],
)
```

project/typescript/app/index.ts
```typescript
import { Person } from "@testlib";
const person: Person = new Person("Jon");
console.log(person.greet());
```

Try to bundle then run the bundled js file or try to run the devserver.

the contents of the bundled file are the same as project/typescript/app/index.ts.

## 🔥 Exception or Error

<pre><code>
No errors occur when running the bundle or devserver command.

However...
Running node on the bundled js output results in "SyntaxError: Cannot use import statement outside a module" message.

Running the devserver and loading the bundled js file results in "SyntaxError: import declarations may only appear at top level of a module" message.

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
archlinux
uname -r
4.19.94-1-lts
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.0.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 24 01:38:42 2019 (1577151522)
Build timestamp: 1577151522
Build timestamp as int: 1577151522
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
http_archive(
  name = "build_bazel_rules_nodejs",
  sha256 = "e1a0d6eb40ec89f61a13a028e7113aa3630247253bcb1406281b627e44395145",
  urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.0.1/rules_nodejs-1.0.1.tar.gz"],
)
"@bazel/rollup": "^1.0.1",
    "@bazel/typescript": "^1.0.1",
  </code>
</pre>

**Comment by alexeagle** [comment]
Are the contents of the bundled file really the same as `index.ts`? I suspect you're just building an ESM-formatted bundle. You can use the https://github.com/bazelbuild/rules_nodejs/blob/1.0.1/docs/Rollup.md#format attribute of `rollup_bundle` to choose a different module syntax in the output.

As for why your lib doesn't get bundled, I tried your repro and see

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@testlib (imported by bazel-out/darwin-fastbuild/bin/typescript/app/index.mjs)
```
in the build output, which means this import statement is broken.
(It would be better for rollup to treat this as an error, perhaps. You can change that behavior in a rollup.config.js file)

So you need to read this documentation about rollup, there's nothing special about Bazel here. It says it only includes library dependencies with relative imports by default, so I find that by changing the import statement in your app/index.ts to `import { Person } from "../testlib/index"` that it works.

(Also note that we don't recommend using the bundled output with a devserver because it makes devmode slow at large-scale. ts_devserver knows how to bundle files on the fly)
