### ISSUE TITLE
Cannot use plain JS sources with TypeScript targets

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/rules_nodejs#1657]
# 🐞 bug report

### Affected Rule

`ts_library`

### Is this a regression?

I don't think so, no

### Description

There should be an ability to use JS sources with the `ts_library` rule, so that one might use the TypeScript compiler to check JS files (via the `allowJs`/`checkJs` compiler flags to `tsc`). Currently, though, trying to use `*.js` sources with `ts_library` yields the error:

```
ERROR: /.../src/BUILD.bazel:9:1: in srcs attribute of ts_library rule //samples/node_mvc/src:JavaScriptController: '//samples/node_mvc/src:JavaScriptController.js' does not produce any ts_library srcs files (expected .ts or .tsx). Since this rule was created by the macro...
```

This is because the [ts_library rule implementation](https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/src/internal/build_defs.bzl#L297) forbids sources with extensions other than `ts, tsx` for `ts_library`.

## 🔬 Minimal Reproduction

**`SomeFile.js`:**
```javascript
// (anything)
```

**`tsconfig.json`:**
```json
{
    "compilerOptions": {
         "allowJs": true,
         "checkJs": true
    }
}
```

**`BUILD.bazel`:**
```starlark
load("@npm_bazel_typescript//:index.bzl", "ts_library")

ts_library(
  name = "SomeFile",
  srcs = ["SomeFile.js"],
)
```

Then:
```
echo "2.1.0" > .bazelversion && bazelisk build //:SomeFile
```

## 🔥 Exception or Error

<pre><code>
ERROR: /.../src/BUILD.bazel:9:1: in srcs attribute of ts_library rule //samples/node_mvc/src:JavaScriptController: '//samples/node_mvc/src:JavaScriptController.js' does not produce any ts_library srcs files (expected .ts or .tsx). Since this rule was created by the macro...
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
    macOS Catalina (10.15.2)
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 2.1.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:04:00 2020 (1581080640)
Build timestamp: 1581080640
Build timestamp as int: 1581080640
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
{
    "devDependencies": {
      "@bazel/bazel": "2.1.0",
      "@bazel/buildifier": "latest",
      "@bazel/ibazel": "^0.12.0",
      "@bazel/jasmine": "^1.2.4",
      "@bazel/karma": "^1.2.4",
      "@bazel/source-map-support": "latest",
      "@bazel/terser": "^1.2.4",
      "@bazel/typescript": "^1.2.4"
    }
}
  </code>
</pre>

`rules_nodejs` version: `1.3.0`

**Comment by Toxicable** [comment]
While I agree that ts_library should take all inputs that normal `tsc` can there are a couple of constraints on it at the moment.  
If you need this feature asap then you can actually use the native tsc directly like so: https://bazelbuild.github.io/rules_nodejs/TypeScript.html#alternatives

**Comment by joeljeske** [comment]
This is tricky since JS and MJS files are generated at the same output path as the source file. It would seem that even manual use of TSC might encounter conflicts noticed by bazel. 

I have run into this issue myself when I want to perform multiple transformation steps on an input file; you have to ensure distinct output paths. 

@Toxicable are you aware of any plans to somehow make output files distinct from source files, perhaps with a different file extension?

**Comment by sgammon** [comment]
@joeljeske good point, perhaps a `.source.js` or something?

mostly my goal here is checking existing js, but compiling ts with js would be nice. checking JS might not need to create files at all

**Comment by alexeagle** [comment]
I think the problem of input artifacts having the same path as output artifacts is orthogonal to the question here which is simply about the restriction we placed on which files are allowed in the srcs of ts_library. I agree it should be relaxed, though we'll need to take care with that change since it wouldn't be desirable in google-internal (they use closure compiler to check .js files and wouldn't want them allowed as srcs of ts_library)

FWIW I should adjust my `ts_project` prototype to allow these inputs https://github.com/alexeagle/ts_composite/blob/master/ts_project.bzl#L10

**Comment by henrysecond1** [comment]
Any updates on this issue? I'm suffering on same issue..

**Comment by alexeagle** [comment]
I think this works with `ts_project`. `ts_library` is kinda stuck until we resolve whether to fork from Google-internal https://github.com/bazelbuild/rules_nodejs/issues/2120

**Comment by ecunal** [comment]
Hey, looks like #2120 is resolved, is there a chance to support JS files with `ts_library` now?

**Comment by alexeagle** [comment]
Sorry I don't think anyone has time or interest to dive into ts_library to add features like this. If you just want to typecheck .js files, ts_project works great.
