### ISSUE TITLE
Support custom flags passed to rollup

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1661]
# 🚀 feature request

### Relevant Rules

`rollup_bundle`

### Description

 A clear and concise description of the problem or missing capability...

It would be useful to allow extra flags to be passed to the rollup binary. Specifically, I want to be able to pass "--silent" to allow bazel to keep a pretty CLI output, but I think it would be useful to allow arbitrary args passed through to support the rest of Rollups API. 

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

Add rule attr 

`args: [ ]`

to the rule `rolllup_bundle`

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

Overriding the rollup tool attr for rollup bundle to set the proc arg before passing on to rollup. Seems a bit overkill

**Comment by alexeagle** [comment]
Seems reasonable to me. But we already have an attribute corresponding to a bunch of flags, like `sourcemap` - if we introduced `args` would we still keep the sourcemap attribute? Want to be consistent about it

**Comment by joeljeske** [comment]
That’s a good point. I think it would be nice to support override flags but I agree it could be confusing. I think the best experience would be to support every rollup flag as an attr but it could be difficult to keep up to date with rollup. 

Comparing to ts_library, we support some options from tsconfig but others are not respected. Would it be so bad to included a set of override args in addition to the current attrs?

**Comment by gregmagolan** [comment]
I'm leaning towards a generic `args` so that users can override config values from their config file if they want to and also adds support for any args that are not available in config files such as `--silent` and `--environment`.

@josephperrott  checked and rollup will error out if there are duplicate args so if a user would to add `--format` it would fail.

In general, however, that would be up to the underlying tool to either handle duplicate CLI args or error out. Should we in general allow users to pass whatever args they want to tools that Bazel invokes?

**Comment by joeljeske** [comment]
Seems like this is fixed as part of https://github.com/bazelbuild/rules_nodejs/pull/1681
