### ISSUE TITLE
Using non-built-in versions from scripts calling `npm`/`yarn`

### ISSUE THREAD

**Issue by gkalpak** [bazelbuild/rules_nodejs#181]
Assuming the following "npm scripts" in `package.json`:

```json
"scripts": {
  "npm-version": "npm -v",
  "yarn-version": "yarn -v",
  ...
```

1. `bazel run @nodejs//:npm run yarn-version` will not use the built-in `yarn`. (This might or might not be by design and the usecase is rather uncommon - so not too worried about this :grin:)

2. `bazel run @yarn//:yarn run yarn-version` will not use the built-in `yarn`. This is quite unexpected.

3. `bazel run @yarn//:yarn run npm-version` will not use the built-in `npm`. This is also quite unexpected.

Related to #140.

**Comment by alexeagle** [comment]
I think we need a variant of our CI that doesn't have any node/npm/yarn installed locally (or we remove it before running tests)

**Comment by gregmagolan** [comment]
Current behavior looks like the Bazel managed npm is used in both cases, `@nodejs//:npm run npm-version` & `@yarn//:yarn run npm-version`, since node is the path to npm/node is always added. And the bazel managed yarn is not used in either case since the path to it is not added.

I think the expected behavior is for the bazel managed yarn & npm to always be used.

**Comment by gregmagolan** [comment]
Correction on last comment. The observed behavior is on OSX and Linux. On windows, there is no bazel managed executable in the path, so the bazel managed npm will not be used in either case as described in the description.
