### ISSUE TITLE
ts_proto_library generates incorrect declaration files for nested protos

### ISSUE THREAD

**Issue by mattsoulanille** [bazelbuild/rules_nodejs#1849]
# 🐞 bug report

### Is this a regression? 
No

### Description

Suppose we have `house.proto` that defines a `House` protobuf and `room.proto` that defines a `Room` protobuf. `House` has the field `kitchen`, which is of type `Room`. 

When `house.proto` is compiled with ts_proto_lib, it produces the following declaration file along with the output js. The bug in this file is that `Room` is imported as `src_room_pb` but `getKitchen()` returns the type `src_room_pbRoom`, which has no definition and is not the correct return type.

```TypeScript
import * as jspb from "google-protobuf"

import * as src_room_pb from '../src/room_pb';

export class House extends jspb.Message {
  getKitchen(): src_room_pbRoom | undefined;
  setKitchen(value?: src_room_pbRoom): void;
  hasKitchen(): boolean;
  clearKitchen(): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): House.AsObject;
  static toObject(includeInstance: boolean, msg: House): House.AsObject;
  static serializeBinaryToWriter(message: House, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): House;
  static deserializeBinaryFromReader(message: House, reader: jspb.BinaryReader): House;
}

export namespace House {
  export type AsObject = {
    kitchen?: src_room_pbRoom.AsObject,
  }
}
```

## 🔬 Minimal Reproduction

https://github.com/mattsoulanille/ts_proto_library_bug

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux [system name] 5.3.0-7648-generic #41~1586789791~19.10~9593806-Ubuntu SMP Mon Apr 13 17:50:40 UTC  x86_64 x86_64 x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
Starting local Bazel server and connecting to it...
Build label: 2.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:01:04 2020 (1581080464)
Build timestamp: 1581080464
Build timestamp as int: 1581080464
Done in 1.29s.
  </code>
</pre>

**Rules_nodejs version:**
<pre>
  <code>
@bazel/labs": "^1.6.0

---------------------------------

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "f9e7b9f42ae202cc2d2ce6d698ccb49a9f7f7ea572a78fd451696d03ef2ee116",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/1.6.0/rules_nodejs-1.6.0.tar.gz"],
)
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment]
@mrmeku have a few minutes to look?

FYI this is from our "labs" package which means support is less than for other packages.

**Comment by cherryland** [comment]
We have the same issue

```skylark
proto_library(
    name = "nested_proto",
    srcs = [
        "proto/car.proto",
        "proto/tire.proto",
    ],
    import_prefix = "awesomecompany/superpackage",
    strip_import_prefix = "/src/testlib/foo/bar/proto",
)

ts_proto_library(
    name = "ts_proto",
    proto = ":nested_proto",
)
```

The output is being generated, but is always empty

```js
// GENERATED CODE DO NOT EDIT
    (function (factory) {
      if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
      }
      else if (typeof define === "function" && define.amd) {
        define("src/testlib/foo/bar/car_pb",  factory);
      }
    })(function (require, exports) {
      
    });
```

**Comment by cherryland** [comment]
`ts_proto_library` only works if you organize your proto definitions in an absolute flat hierarchy.

This means you have some top directory eg. `/protos` which contains all your proto definitions.

Otherwise the rule won't work. This can also be seen in [examples/protocol_buffers](https://github.com/bazelbuild/rules_nodejs/tree/master/examples/protocol_buffers): Everything is flat. 

If you use the [Google approach](https://github.com/googleapis/googleapis/tree/master/google) to organize and structure proto definitions, than `ts_proto_library` is definitely not for you.

The alternative is `protobufjs_ts_library`, but it generates horribly monolithic code, pure garbage ES3 syntax. Definition of lesser of two evils.

**Comment by cherryland** [comment]
If you `print(protoc_command)` in [ts_proto_library.bzl#L82](https://github.com/bazelbuild/rules_nodejs/blob/master/packages/labs/src/grpc_web/ts_proto_library.bzl#L82), strip the output it from the grpc_web plugin weirdness and run it

```sh
$ protoc <protoc_command>
```

it actually builds the files and just works

**Comment by zhuhaow** [comment]
The real issue is the `ts_proto_ilbrary.bzl` set `input_base_path` incorrectly for `change_import_style`, the real path should be the package name of the proto (taking strip/append etc into consideration), but the path is set to the path of the proto file.

**Comment by alexeagle** [comment]
@zhuhaow sounds like you understand the problem pretty well, want to try a pull request to fix it?

**Comment by zhuhaow** [comment]
I'm not quite sure if this is really a bug or not. 

The issue only happens when the project is not organized in the "bazel" way, i.e., the proto target is not defined in the BUILD file in the same folder, or the folder hierarchy is not correctly mapped to the proto package definition. A proto with package name `foo.bar` should be located in `foo/bar.proto` and defined in `foo/BUILD.bazel` as `bar_proto`. `bar_proto` should only have one source file. This is actually only recommended instead of enforced by the [`proto_rule`](https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library), but is somehow implied by the current `ts_proto_ilbrary.bzl`.

But it doesn't mean we can "fix" it, even if we want to. 

Say our current project has two proto files, `proto/foo/bar.proto` with package name `foo.bar` and `proto/foo/foo/bar.proto` with package name `foo.foo.bar`, they are defined in the `p/foo/BUILD.bazel` as `bar_proto`. Then the protoc generator would generate js code as `BIN_DIR/foo/bar.ts` and `BIN_DIR/foo/foo/bar.ts`. We can't have final output not in our current package, the `proto/foo` package, so we should copy the generated files into the `BIN_DIR/proto/foo/`. But there is no reasonable way of doing it. The expected path should be `foo/bar.ts` which will then be imported as `import * from foo.bar` but we simply can't archive that. If the user goes further by sharing the same package name among these two files, the output would overwrite the earlier generated one.

This won't be an issue for targets outputting compiled results, e.g., java or cc, where the output location has nothing to do with the import package name. I don't think we will have a good solution other than letting users know it only works with well-organized projects.

**Comment by mrmeku** [comment]
@zhuhaow I think this is a bug as far as messaging goes. We could definitely have the tool tell you if you violate its requirement that the `ts_proto_library` target be in the same directory as the proto itself.

If that sort of messaging would have been communicated to you, would that have been sufficient to resolve the issue?

**Comment by zhuhaow** [comment]
It should be very helpful. 

The requirements should be the BUILD.bazel file needs to located in the path correctly mapping to the package name of the proto, i.e., package `foo.bar` needs to be defined in path `foo/bar/BUILD.bazel`. The location of the proto file is actually not important.

**Comment by zhuhaow** [comment]
After inspecting the behavior of other generator plugins, e.g., https://github.com/google/protobuf-gradle-plugin

I found the generally expected behavior should be ignoring the package defined in the proto but take the path to the proto as the import package name. AFAIK this is possible. I'll send out a PR later.
