### ISSUE TITLE
Can the results of npm_install or yarn_install be cached remotely?

### ISSUE THREAD

**Issue by zhuhaow** [bazelbuild/rules_nodejs#1968]
I can't find it documented anywhere.

Test with `--disk_cache` suggests the results are not cached at all. 

For yarn, the [1] resolve dependencies and [2] fetching packages stages finish in seconds since the results are cached by yarn. Then the [3] linking dependencies and [4] building fresh package take a very long time after a `bazel clean`.

This is rather painful since the angular `ngcc` would build every package everytime `yarn install` is invoked. 

Things get worse on CI since [1][2] are also not cached thus takes bazel about 5 minutes to set up the workspace.

I'm not sure if this is some misconfiguration on my side or this is the expected behavior. If this is expected, can we [cache node_modules](https://medium.com/vendasta/how-to-speed-up-angular-build-times-with-caching-5856d369de88)? If caching node_modules might cause issues, can we cache the yarn cache folder?

**Comment by zhuhaow** [comment]
More information. 

If `symlink_node_modules` is set to `True`, things will be much better, the second invocation of `yarn install` would complete almost immediately, even after a `bazel clean` which is awesome. I was setting it to false since I was trying to use two different `package.json`s in one folder and I found it not well supported.

Of course, this won't help much on CI.

**Comment by alexeagle** [comment]
No I don't think there's any mechanism in Bazel for repository rules results to be in a remote cache. This is because the rules are non-hermetic by design so there's no way to ensure that a remote cache hit is viable on your machine state.

You should make sure that your CI system is configured to persist the yarn cache across workers, in the same way you would do without bazel, and also that the Bazel --repository_cache directory is persisted. (Note, I think we are missing this setting in our own CircleCI setup here: https://github.com/bazelbuild/rules_nodejs/blob/1.x/.circleci/config.yml#L109)

**Comment by zhuhaow** [comment]
Thanks, Alex. Caching yarn cache and node_module works like a charm.
