### ISSUE TITLE
No 'bazel-out' folder found in path <TMP_DIR> after migration to rules_nodejs 2.0.0

### ISSUE THREAD

**Issue by davido** [bazelbuild/rules_nodejs#1977]
We are trying to migrate Gerrit Code Review to `rules_nodejs` 2.0.0: [1]

To run polymer liniting tests, the script doing this:

```
#!/bin/bash
  
set -ex

DIR=$(pwd)
ln -s $RUNFILES_DIR/ui_npm/node_modules $TEST_TMPDIR/node_modules
cp $2 $TEST_TMPDIR/polymer.json
cp -R -L polygerrit-ui/app/* $TEST_TMPDIR

#Can't use --root with polymer.json - see https://github.com/Polymer/tools/issues/2616
#Change current directory to the root folder
cd $TEST_TMPDIR/
$DIR/$1 lint --verbose
```

After the migration the test is failing with:

```bash
INFO: Found 1 test target...
SUBCOMMAND: # //polygerrit-ui/app:polylint_test [action 'Testing //polygerrit-ui/app:polylint_test', configuration: 3d581e0a740959a18e00d82fc52ed9b13129a87c1fc89503a5ee14bee5b892d3, execution platform: @local_config_platform//:host]
(cd /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit && \
  exec env - \
    EXPERIMENTAL_SPLIT_XML_GENERATION=1 \
    JAVA_RUNFILES=bazel-out/k8-fastbuild/bin/polygerrit-ui/app/polylint_test.runfiles \
    PATH=/home/davido/.yarn/bin:/home/davido/.config/yarn/global/node_modules/.bin:/home/davido/pgm/apache-maven-3.5.2/bin:/home/davido/bin:/home/davido/.yarn/bin:/home/davido/.config/yarn/global/node_modules/.bin:/home/davido/pgm/google-cloud-sdk/bin:/home/davido/pgm/apache-maven-3.5.2/bin:/home/davido/bin:/home/davido/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin \
    PYTHON_RUNFILES=bazel-out/k8-fastbuild/bin/polygerrit-ui/app/polylint_test.runfiles \
    RUNFILES_DIR=bazel-out/k8-fastbuild/bin/polygerrit-ui/app/polylint_test.runfiles \
    RUN_UNDER_RUNFILES=1 \
    TEST_BINARY=polygerrit-ui/app/polylint_test \
    TEST_INFRASTRUCTURE_FAILURE_FILE=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.infrastructure_failure \
    TEST_LOGSPLITTER_OUTPUT_FILE=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.raw_splitlogs/test.splitlogs \
    TEST_PREMATURE_EXIT_FILE=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.exited_prematurely \
    TEST_SIZE=large \
    TEST_SRCDIR=bazel-out/k8-fastbuild/bin/polygerrit-ui/app/polylint_test.runfiles \
    TEST_TARGET=//polygerrit-ui/app:polylint_test \
    TEST_TIMEOUT=900 \
    TEST_TMPDIR=_tmp/b2d5eee52f25e7b97908b20a944ee7f4 \
    TEST_UNDECLARED_OUTPUTS_ANNOTATIONS=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.outputs_manifest/ANNOTATIONS \
    TEST_UNDECLARED_OUTPUTS_ANNOTATIONS_DIR=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.outputs_manifest \
    TEST_UNDECLARED_OUTPUTS_DIR=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.outputs \
    TEST_UNDECLARED_OUTPUTS_MANIFEST=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.outputs_manifest/MANIFEST \
    TEST_UNDECLARED_OUTPUTS_ZIP=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.outputs/outputs.zip \
    TEST_UNUSED_RUNFILES_LOG_FILE=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.unused_runfiles_log \
    TEST_WARNINGS_OUTPUT_FILE=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.warnings \
    TEST_WORKSPACE=gerrit \
    TZ=UTC \
    XML_OUTPUT_FILE=bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.xml \
  external/bazel_tools/tools/test/test-setup.sh polygerrit-ui/app/polylint_test external/tools_npm/polymer-cli/bin/polymer.sh polygerrit-ui/app/polymer.json)
SUBCOMMAND: # //polygerrit-ui/app:polylint_test [action 'Testing //polygerrit-ui/app:polylint_test', configuration: 3d581e0a740959a18e00d82fc52ed9b13129a87c1fc89503a5ee14bee5b892d3, execution platform: @local_config_platform//:host]
(cd /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit && \
  exec env - \
    PATH=/usr/bin:/bin \
    TEST_BINARY=polygerrit-ui/app/polylint_test \
    TEST_NAME=//polygerrit-ui/app:polylint_test \
    TEST_SHARD_INDEX=0 \
    TEST_TOTAL_SHARDS=0 \
  external/bazel_tools/tools/test/generate-xml.sh bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.log bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.xml 0 1)
FAIL: //polygerrit-ui/app:polylint_test (see /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.log)
INFO: From Testing //polygerrit-ui/app:polylint_test:
==================== Test output for //polygerrit-ui/app:polylint_test:
++ pwd
+ DIR=/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/bazel-out/k8-fastbuild/bin/polygerrit-ui/app/polylint_test.runfiles/gerrit
+ ln -s /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/bazel-out/k8-fastbuild/bin/polygerrit-ui/app/polylint_test.runfiles/ui_npm/node_modules /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/_tmp/b2d5eee52f25e7b97908b20a944ee7f4/node_modules
+ cp polygerrit-ui/app/polymer.json /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/_tmp/b2d5eee52f25e7b97908b20a944ee7f4/polymer.json
+ cp -R -L polygerrit-ui/app/behaviors polygerrit-ui/app/constants polygerrit-ui/app/elements polygerrit-ui/app/embed polygerrit-ui/app/gr-diff polygerrit-ui/app/polylint_test polygerrit-ui/app/polylint_test.sh polygerrit-ui/app/polymer.json polygerrit-ui/app/rollup.config.js polygerrit-ui/app/scripts polygerrit-ui/app/services polygerrit-ui/app/styles polygerrit-ui/app/types polygerrit-ui/app/utils polygerrit-ui/app/wct.conf.js /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/_tmp/b2d5eee52f25e7b97908b20a944ee7f4
+ cd /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/_tmp/b2d5eee52f25e7b97908b20a944ee7f4/
+ /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/bazel-out/k8-fastbuild/bin/polygerrit-ui/app/polylint_test.runfiles/gerrit/external/tools_npm/polymer-cli/bin/polymer.sh lint --verbose
[link_node_modules.js] Error: Internal error! Please run again with
   --define=VERBOSE_LOG=1
and file an issue: https://github.com/bazelbuild/rules_nodejs/issues/new?template=bug_report.md
Include as much of the build output as you can without disclosing anything confidential.

  Error:
  No 'bazel-out' folder found in path '/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/_tmp/b2d5eee52f25e7b97908b20a944ee7f4'!
  
    at panic (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/build_bazel_rules_nodejs/internal/linker/index.js:23:11)
    at /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/build_bazel_rules_nodejs/internal/linker/index.js:79:13
    at Generator.next (<anonymous>)
    at /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/build_bazel_rules_nodejs/internal/linker/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/build_bazel_rules_nodejs/internal/linker/index.js:4:12)
    at resolveRoot (/home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/build_bazel_rules_nodejs/internal/linker/index.js:73:12)
    at /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/build_bazel_rules_nodejs/internal/linker/index.js:340:31
    at Generator.next (<anonymous>)
    at /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/external/build_bazel_rules_nodejs/internal/linker/index.js:8:71
================================================================================
Target //polygerrit-ui/app:polylint_test up-to-date:
  bazel-bin/polygerrit-ui/app/polylint_test
INFO: Elapsed time: 0.956s, Critical Path: 0.45s
INFO: 2 processes: 2 local.
INFO: Build completed, 1 test FAILED, 3 total actions
//polygerrit-ui/app:polylint_test                                        FAILED in 0.1s
  /home/davido/.cache/bazel/_bazel_davido/5c01f4f713b675540b8b424c5c647f63/execroot/gerrit/bazel-out/k8-fastbuild/testlogs/polygerrit-ui/app/polylint_test/test.log

INFO: Build completed, 1 test FAILED, 3 total actions
```

To reproduce, clone gerrit, apply: [1] and run:

```
  $ bazel test -s --define=VERBOSE_LOG=1 //polygerrit-ui/app:polylint_test 
```

[1] https://gerrit-review.googlesource.com/c/gerrit/+/273256

**Comment by alexeagle** [comment]
@davido found some time today to repro this.

To understand the problem, see the Linker section in the 2.0 breaking changes
https://github.com/bazelbuild/rules_nodejs/releases/tag/2.0.0-rc.0

Most of the time when you run a node program under Bazel, you first want the `node_modules` directory to have your first-party packages linked (in the "npm link") sense. So our `launcher.sh` that wraps node now defaults to running that linker, and it expects some environment. In your test, you bring the nodejs_binary and execute it yourself, so it isn't passed an argument with a modules manifest of things to link, and the chdir in this test is also making it not find the bazel-out folder. (if I remove the chdir, there's no error from the linker, the polymer CLI tool runs and complains it didn't find polymer.json)

You can disable the linker as we indicate in the 2.0 release notes: in `polylint_test.sh`, change the last line to
`$DIR/$1 --nobazel_run_linker lint --verbose`

I then get a different error

```
+ /private/var/tmp/_bazel_alex.eagle/ea778b5c9af68d802a0dccaac8e08d8a/execroot/gerrit/bazel-out/darwin-fastbuild/bin/polygerrit-ui/app/polylint_test.runfiles/gerrit/external/tools_npm/polymer-cli/bin/polymer.sh --nobazel_run_linker --bazel_patch_module_resolver lint --verbose


import 'polymer-bridges/polymer/lib/utils/boot_bridge.js';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

scripts/bundled-polymer.js(28,1) warning [cant-resolve-module-specifier] - Cannot resolve module specifier with resolution algorithm: node
```
I'm not sure if that's related. I assume you'll be better able to debug that since I think this is polymer CLI doing custom resolve? Ideally we should figure that out before I declare that this is Working as Intended.

(Unrequested design feedback: at a high level, I'm surprised that this test runs the nodejs_binary, rather than bazel running it to produce some linter output and then the test asserting on that output)

**Comment by alexeagle** [comment]
Oh, here's the idiomatic way I would do this:

grab the "_test" variant of the generated polymer-cli rule, and also a helper to write a file

```
load("@tools_npm//polymer-cli:index.bzl", "polymer_test")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
```

then to replicate your `cd` command since polymer wants the working directory to be in your package, write a little JS file that does the process.chdir after node starts

```
write_file(
    name = "write_chdir_script",
    out = "chdir.js",
    # __dirname will be whatever directory the other outputs
    # from this package are in.
    content = ["process.chdir(__dirname)"],
)
```

and now your sh test needs to `--require` that chdir so it happens before polymer runs

```

polymer_test(
    name = "polylint_test",
    size = "large",
    args = [
        "--node_options=--require=./$(rootpath chdir.js)",
        "lint",
        "--verbose",
    ],
    data = [
        "chdir.js",
        "polymer.json",
        ":polylint-fg",
        # "@ui_npm//:node_modules",
    ],
    # Should not run sandboxed.
    tags = [
        "local",
        "manual",
    ],
)
```

this is close to working, but fails on a bunch of imports. I think you're relying on running a program with more than one node_modules - one with UI dependencies and one for tools - and that's not really npm-idiomatic and we don't support it in rules_nodejs. So I wasn't able to get this green yet but I hope it demonstrates how this is meant to work.

**Comment by davido** [comment]
@alexeagle Thanks for the analysis. I created this issue in gerrit to follow-up: [1].

[1] https://bugs.chromium.org/p/gerrit/issues/detail?id=13090

**Comment by gdmfilippov** [comment]
@alexeagle Why can't we run a script from an arbitrary directory? This is a very strict limit.
Npm modules resolution algorithm allows to place script anywhere on your filesystem and then user can run it in any working directory. Typical scenario - install a script in a global node_modules and then run it inside your working directory; I saw this approach in many npm-based tools.

I think, it should be possible to fix launcher.sh and/or generated .sh script (for npm module) to not use working directory (at least, I don't see why it is not possible). 

> I think you're relying on running a program with more than one node_modules - one with UI dependencies and one for tools - and that's not really npm-idiomatic 

I don't agree, that this is not npm-idiomatic. Without bazel there are 2 main scenarios how to separate UI dependencies and tools:
1) Install tools in global npm_modules. Keep UI packages in local package.json
2)Use devDependencies for tools. When deploying to a server - install only non-dev dependencies.
Such separation is very important and allows to use "unsafe" packages for development and have a full control over what is using in production.

Both scenarios are not supported by rules_nodejs directly. So, we decided to use a separate node_modules for tools (it is like using global npm_modules).

Scenario with devDependencies is not possible, because we can't install package.json twice in bazel - once with devDependencies and once without devDependencies - and use them separately.

**Comment by gdmfilippov** [comment]
@alexeagle Slightly offtopic ,but Ideally, I would like to have a nodejs_binary rules to produce an "isolated" tool. Isolated - I mean, that the tool can be run anywhere, just like any other sh_binary.
For example:
```nodejs_binary(
        name = name + "_bin",
        entry_point = "@npm//:node_modules/eslint/bin/eslint.js",
        data = [...] #List of plugins for eslint
```
I can imagine, that nodejs_binary creates a separate directory for this binary and put all required files into it. For npm modules it creates node_modules subdir in the created directory and then installs/links all necessary modules there. Also put .sh script into this directory.

Such script can be run anywhere, in any working directory where other node_modules directory exists and node_modules are not conflicting (because require(...) call in node always looking for a module relative to a caller and doesn't use working directory for module resolving).

**Comment by alexeagle** [comment]
Hi @gdmfilippov 

Re. two node_modules directories:
I thought about this more last night after writing that. For your case 2: actually this is still one node_modules folder, devDeps doesn't influence either how node_modules are laid out nor how they are resolved. You just promise to your users that you won't require() a devDep at runtime. And package managers have a flag like `--prod` to give you a different node_modules layout where devDeps are omitted. So for case 2 I still claim that rules_nodejs is giving all the same affordances that node idioms do.

However for case 1 you are right, a layout like project/node_modules and project/subdir/node_modules is how yarn workspaces lets code in subdir/ require() things from either node_modules. When we run our linker, we should be able to reproduce the same layout in execroot/runfiles to allow the same resolution. It will take a bunch of thinking about how that interacts with everything else, but it feels promising to me as a way to finally support yarn workspaces and let you dep on a tree of node_modules directories (and their respective external repositories). This would have to go on our roadmap.

Re. run a script from an arbitrary directory: you totally can, it just has this bad interaction with our linker process. I saw there was another similar report about our rc.0 release so I think we should do a bit more in the linker to detect this case and either keep going or fail with a better message. Ideally like you say, we shouldn't be sensitive to working directory at all.

Let me also clarify: while I think the *right* way to run polymer as a test is to load `polymer_test`, we should still support using a nodejs_binary in some novel way like this. Bazel's runfiles makes programs appear to be packaged up in this way, but the Windows support is so bad we've been trying to avoid depending on it. I think https://github.com/bazelbuild/rules_nodejs/issues/1910 captures your use case (since a test depending on a binary is just a special case of a binary depending on a binary) so let's follow up on that topic there.

**Comment by alexeagle** [comment]
I filed that #2002 to capture the root cause that I think we ought to fix

**Comment by alexeagle** [comment]
#266 is the right place to follow-up about having tools in the root package.json and UI libs in a nested one

**Comment by davido** [comment]
Thanks for the follow-ups, closing.

**Comment by davido** [comment]
@alexeagle 

> So, changing your last line to $DIR/$1 --nobazel_run_linker --nobazel_node_patches lint --verbose makes this test pass.

True, but it appears to not to do anything and returning always after 0.1 second.

To reproduce we have uploaded this Polymer breakage change: [1] that is detected and correctly reported by `polymer lint` check:


Now, we have rebased the `rules_nodejs` upgrade change on top of Polymer lint brekage change and would have expected to replicate the same breakage also after the upgrade.

However, after the migration to rules_nodejs 2.0.0.rc.1 and after changing the last line in `polylint_test.sh` to:

```
[...]
  $DIR/$1 --nobazel_run_linker --nobazel_node_patches lint --verbose 
```

the `polymer lint` test actually succeeded, and turning to be a no op check.

Note though, that we are thinking about removal of Polymer lint check altogether, and I even uploaded a change that would do it: [2], but I thought we should try to uderstand, why `polymer lint` is broken now after the `rules_nodejs` upgrade, thus re-opening this issue again.

[1] https://gerrit-review.googlesource.com/c/gerrit/+/274692
[2] https://gerrit-review.googlesource.com/c/gerrit/+/273256

**Comment by gdmfilippov** [comment]
After the previous @davido comment, we made some research and found a workaround.

It seems, that flags --nobazel_run_linker --nobazel_node_patches are lost in the following scenario:
```
# BUILD file
sh_test(
    name = "polylint_test",  
    srcs = ["polylint_test.sh"],
    args = [
        "$(location @tools_npm//polymer-cli/bin:polymer)",
    ]
)

# polylint_test.sh
$DIR/$1 --nobazel_run_linker --nobazel_node_patches lint
```

However, if we wrap the @tools_npm//polymer-cli/bin:polymer script into our own nodejs_binary, the problem is gone (see https://gerrit-review.googlesource.com/c/gerrit/+/274698/1):
```
nodejs_binary(
    name = "polymer_cli",
    data = ["@tools_npm//polymer-cli"],
    entry_point = "@tools_npm//:node_modules/polymer-cli/bin/polymer.js",
    templated_args = [
        "--nobazel_run_linker",
        "--nobazel_node_patches",
    ],
)

# BUILD file
sh_test(
    name = "polylint_test",  
    srcs = ["polylint_test.sh"],
    args = [
        "$(location @tools_npm//polymer-cli/bin:polymer)",
    ]
)

# polylint_test.sh
$DIR/$1 lint
```

We are going to use this workaround.

**Comment by davido** [comment]
Thanks @gdmfilippov for the update.

 I think you have a typo in your second `BUILD` file listing, as the reference to the newly created `polymer_cli` is missing. It should be:

```python
sh_test(
    name = "polylint_test",
    size = "large",
    srcs = ["polylint_test.sh"],
    args = [
        "$(location :polymer_cli)",
        "$(location polymer.json)",
    ],
    data = [
        "polymer.json",
        ":polylint-fg",
        ":polymer_cli",
    ],
    # Should not run sandboxed.
    tags = [
        "local",
        "manual",
    ],
)
```

@alexeagle 

Why this wrapper is actually needed? Is this eventually another known issue?

**Comment by alexeagle** [comment]
I would expect that any means of passing those flags as arguments to the program should have the same effect, whether they are templated_args of a nodejs_binary or passed to an invocation of that binary. But wrapping it that way looks fine to me, I don't have much time this week to dig into this more.

**Comment by davido** [comment]
I was experimenting again with the direct call, of `polymer.sh` 
and it turns out that this works:

```
$DIR/$1 --nobazel_run_linker lint --verbose
```

and it works as expected:

```
            '_updateSideClasses(side)',
             ~~~~~~~~~~~~~~~~~~

elements/diff/gr-diff-cursor/gr-diff-cursor.js(105,14) warning [databinding-calls-must-be-functions] - _updateSideClasses is not a known method on gr-diff-cursor


Found 1 warning.
================================================================================
Target //polygerrit-ui/app:polylint_test up-to-date:
  bazel-bin/polygerrit-ui/app/polylint_test
INFO: Elapsed time: 13.393s, Critical Path: 12.84s
INFO: 2 processes: 2 local.
INFO: Build completed, 1 test FAILED, 3 total actions
//polygerrit-ui/app:polylint_test                                        FAILED in 12.5s
```

Passing in addition: `--nobazel_node_patches` actually broke it.

**Comment by davido** [comment]
Closing as the patch set 6 works as expected.

For the record, the solution was to pass: `--nobazel_run_linker` to node launcher.
