### ISSUE TITLE
Jest is not ibazel aware and completely restarts

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#2028]
Jest has a nice watch mode, but of course it doesn't know to re-do parts of the build before executing tests.
You could imagine adding a Bazel plugin to Jest, so that Jest watches files and invokes Bazel before testing, but this is backwards, and Jest cannot know all the things in the monorepo it must watch that might affect outputs it tests.

The right answer is for us to contribute a custom watcher for Jest that is ibazel-aware. Maybe maybe we can hack it in with a `--require` script. Similar issue to our devserver workflows that do restarts.

/cc @mrmeku

**Comment by alexeagle** [comment]
I brain dumped into https://hackmd.io/xst6eshlQUi3EtL8XfAizg

**Comment by valgussev** [comment]
Hi @alexeagle, any recent activity on ibazel-aware jest?

**Comment by jcready** [comment]
How is this still the most relevant issue about getting Jest (almost certainly the most used test runner/framework for JS) to work with ibazel (almost certainly the worst named thing only after "bazel watch" which returns completely irrelevant search results)?

How I long for the days when I could use Jest w/o Bazel and all my tests ran quickly instead of slow as molasses.

**Comment by gregmagolan** [comment]
@jcready rules_nodejs is no longer actively maintained so this issue is unlikely to get addressed here unless someone steps up to do the work.

All of the past maintainers have moved onto [rules_js](https://github.com/aspect-build/rules_js) where [rules_jest](https://github.com/aspect-build/rules_jest) provides support for Jest with Bazel. rules_jest has built-in support for hermetic snapshot updates, sharding and JUnit XML reporting with Bazel. It is not yet have incremental ibazel watch mode. It is not trivial addition and likely to be at least at week of work to get the wiring right with Jest. It could be done, however, if there was funding for the work either through our [professional services ](https://www.aspect.dev/) or through open collective https://opencollective.com/aspect-build/projects/rules_js.
