### ISSUE TITLE
Provide an rlocation function for JS similar to other langs

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#204]
https://github.com/bazelbuild/bazel/issues/4460 is introducing language-specific utilities to access runfiles paths in a platform-independent way (meaning read through the runfiles MANIFEST file on Windows)

We should provide a function in JS with the same API and semantics, and switch our rules to it.

**Comment by gregmagolan** [comment]
This is included in https://github.com/bazelbuild/rules_nodejs/pull/243/files and will be resolved when that lands.

**Comment by alexeagle** [comment]
@gregmagolan so is this done now?

**Comment by gregmagolan** [comment]
We were able to accomplish this just using `require.resolve()` in node since we override the default behavior:

https://github.com/bazelbuild/rules_nodejs/pull/243/files#diff-b2e984df3ce197f89cc3e22b698aad28R63
https://github.com/bazelbuild/rules_nodejs/pull/243/files#diff-14d12326e9e24e7a9e2705a5d99b509dR86

Downside is that spawned node processed don't inherit the overloaded resolver. Looking to resolve this in the future by configuring runfiles so that the native node resolve works under Bazel:

https://github.com/bazelbuild/rules_nodejs/issues/315
https://github.com/bazelbuild/rules_nodejs/issues/312
