### ISSUE TITLE
Update documentation style

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_nodejs#2105]
# 🚀 feature request

### Description

The documentation is incredibly difficult to parse and seem quite different from every other set of rules

[rules_swift](https://github.com/bazelbuild/rules_swift/tree/master/doc)
[rules_cc](https://docs.bazel.build/versions/master/be/c-cpp.html)
[rules_rust](https://bazelbuild.github.io/rules_rust/rust.html)

### Describe the solution you'd like

The documentation should be restructured such that each rule has a table that describes all of it's attributes

<img width="935" alt="Screen Shot 2020-08-11 at 12 46 54 PM" src="https://user-images.githubusercontent.com/26427366/89942180-f3e87600-dbd0-11ea-94e5-d00d18b10c07.png">
<img width="929" alt="Screen Shot 2020-08-11 at 12 47 06 PM" src="https://user-images.githubusercontent.com/26427366/89942184-f4810c80-dbd0-11ea-8866-94cbea1985f8.png">

### Describe alternatives you've considered

I'm not sure what the workaround should be. My reference to `rules_cc` is just a suggestion. There's likely a bunch of ways to improve readability but I do feel it's a problem with these rules.

**Comment by mattem** [comment]
Thanks for the issue, we spoke about a design refresh in our teams meeting today, so this is good timing.
I think this is something we can look into doing, there are a few other bits that need fixing with the doc generation too while we are in there.

**Comment by UebelAndre** [comment]
@mattem Hey, thanks for the quick reply 😃

Is there an issue tracking those things you mentioned you want to do?

**Comment by mattem** [comment]
I don't think there are separate issues for each item on the list, but this is what springs to mind:

* Docs search isn't working #1282
* Since switching to stable as the default branch, it's a manual step in the release to push to master for the doc site
* There are references to the internal `//packages` labels still in some documented rules and examples, we should apply the same substitutions to the docsgen as to the published packages
* In order to flip `--incompatible_no_rule_outputs_param`, we need to address some doc generation issues around macros #1303

Also, it kinda irks me that there isn't a consistent style for the canonical rule sets in the bazelbuild org, but that's outside the scope here I think

**Comment by UebelAndre** [comment]
@mattem Awesome! All those things sound super exciting! Thanks so much for sharing, I really appreciate it 😃

**Comment by mattem** [comment]
#2122 now merged, and live at https://bazelbuild.github.io/rules_nodejs/
I think I'll close this, and we can now open more focused issues for follow up items

**Comment by UebelAndre** [comment]
It looks way better! Thank you so much!
