### ISSUE TITLE
Recommend setting `sourceRoot: "/"` in `tsconfig.json` to generate sane sourcemaps

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_nodejs#2153]
# 🚀 feature request

### Relevant Rules

`ts_library`

### Description

Typescript generates sourcemap source file path based on `files` config, however, which is relevant to where the `tsconfig.json` placed. Hence the generated source map contains dozens of double-dots (`..`) in the source name and makes debugging a [nightmare](https://bazelbuild.github.io/rules_nodejs/debugging.html#debugging-with-vs-code). 

### Describe the solution you'd like

Set `sourceRoot: "/"` in the `tsconfig.json` to let tsc to resolve source file names correctly. 

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by alexeagle** [comment]
From the perspective of the output tree, what typescript writes is already "correct", in the sense that you have a file

bazel-out/[arch]/bin/path/to/file.js
with a sourcemap pointing to
../../../../../path/to/file.ts
and that's the correct way to reference back from the output tree to the source tree.

However you could be using a `dist/bin` symlink to point to `bazel-out/[arch]/bin` so now you want two `../..` instead of three `../../..` - so there is no one right path to put into the sourcemaps.

Note that this applies to all languages. You'll see the same thing running sass for example.

If you're going to shuffle files around later such that file.js appears in the same directory with file.ts then maybe you'd like the sourcemaps to be different, but that should be a responsibility of whatever does the shuffling.

You can always set `sourceRoot` in the tsconfig yourself, right? I haven't tried that with `ts_library` but I expect it would work with `ts_project`

**Comment by ashi009** [comment]
Sounds fair. Closing.
