### ISSUE TITLE
How to Cache the node_modules/.cache Directory When Running Tests?

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2200]
🐞 bug report

### Affected Rule
The issue is caused by the rule: `jasmine_node_test` (kind of)

### Description
I am using [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server) to test code, which interacts with a Mongo database.

As my test runner I use [Jasmine](https://jasmine.github.io).

Running my test with `ts-node node_modules/jasmine/bin/jasmine --config=jasmine.json` takes around 2 seconds.

Unfortunately running my tests with Bazel via `bazelisk test //...` takes a few **minutes**, because it will always re-download the `mongod` binaries needed by the mongodb-memory-server package. **This is really annoying when having slow internet as I do!**

## 🔬 Minimal Reproduction

I've made a small repro: [flolu/bazel-mongodb-memory-server](https://github.com/flolu/bazel-mongodb-memory-server) showcasing the problem.

### How can I configure Bazel, such that it won't re-download the binaries every time?

In the [documentation](https://github.com/nodkz/mongodb-memory-server#mongodb-memory-server) they state, that the binary is stored in `node_modules/.cache/mongodb-binaries`. Thus my guess is that Bazel won't cache the `node_modules/.cache` directory.

**Comment by alexeagle** [comment]
Bazel caches the state of the node_modules as they existed after `yarn_install` or `npm_install` finishes, after that any mutations to the node_modules that happen during a build action or test execution will be lost, yes. I bet you can add a `postinstall` that causes mongod to be downloaded into the node_modules copy that Bazel sees, rather than rely on the first action/test that runs it.

**Comment by thesayyn** [comment]
We've had this exact issue with the "mongodb-memory-server-core" package. What we've done was set the cache directory to Bazel's sandbox root thus we had cache across sandboxes.

**Comment by alexeagle** [comment]
How do you set the cache directory? I didn't see that in the doc

**Comment by thesayyn** [comment]
Through downloadDir option or MONGOMS_DOWNLOAD_DIR environment variable.

**Comment by flolu** [comment]
@thesayyn Do you mind providing an example? I not sure where to configure those environment variables.

**Comment by thesayyn** [comment]
Environment variable thing won't work for bazel. You have to use the downloadDir option while constructing the MongoMemoryServer class.Which would then point to the sandbox root. 
You can see it in the readme of the github page of the package

**Comment by flolu** [comment]
@thesayyn I see, that makes sense. How can I get a reference to the sandbox root path in the Typescript code?

**Comment by thesayyn** [comment]
I don't remember which environment variable was it but if you check out the process.env you'll see an environment variable whose value contains `sandbox-`.   When you find that variable, all you have to do is remove the path segments until you reach the sandbox segment. 

That said, we had used this approach for a few months, and does not work well as the number tests grow exponentially over time. As the number of tests grows, number of forked mongodb servers grows as well therefore leading to resource starving.
At that point you have to choose between concurrency and stability and you can't give up on concurrency.

At spica, we have tricked the bazel to share a single mongodb server across concurrent tests using bazel's worker mode.
What we have done is, we've created a simple rule that runs the mongodb server and when it gets ready, we write a json file to the `runfiles` that will later be consumed by `MongoClient`. 

See the full implementation here:
https://github.com/spica-engine/spica/tree/master/packages/database/testing


Worker that is ran by bazel

https://github.com/spica-engine/spica/blob/master/packages/database/testing/worker.js
A simple script that uses `@bazel/worker` to run in worker mode. This worker simply forks a mongodb server using `mongodb-memory-server-core` when bazel sends the compilation request and as soon as the server gets up it creates a a json file to be consumed by `start.ts`


Part that runs on the jasmine process in `beforeEach`; 

https://github.com/spica-engine/spica/blob/master/packages/database/testing/start.ts. 
As you can see just a simple function that connects to the database by requiring json files that have been created by worker.

Keep in mind that this approach also has a downside; you loose the test caching. because whenever a test starts after a freshly started bazel server, we have to check if the worker is still alive. in order to do that we have to disable/bust bazel's caching mechanism on this rule. (which is not possible by time i write this.)

So what we do is simple, in order to bust the cache we give the rule a simple text file as an input. Also, we create a stamping script that writes the date into this whenever invoked. So bazel runs this script before running tests and that script writes the date to the text file and bazel sees it as a change and runs the worker again.

**Comment by thesayyn** [comment]
Also; to overcome the last issue in my approach we could do what ever bazels web testing rule does.

**Comment by flolu** [comment]
Wow that's a lot, thank you! :laughing:

The solution with the Bazel worker seems like the way to go, but I will probably stick with setting the `downloadDir` until the caching problem has a solution.

Also, I've now tried to set the `downloadDir` with this code:
```
console.log(process.env.RUNFILES)
// ../home/flolu/.cache/bazel/_bazel_flolu/7213acaffdabec4878e1d1fe276483d0/sandbox/linux-sandbox/212/execroot/drakery/bazel-out/k8-fastbuild/bin/packages/event-sourcing/test.sh.runfiles
let tmp = path.parse(process.env.RUNFILES)
while (tmp.name !== 'sandbox') {
  tmp = path.parse(tmp.dir)
}
const sandboxPath = path.format(tmp)
console.log(sandboxPath)
// /home/flolu/.cache/bazel/_bazel_flolu/7213acaffdabec4878e1d1fe276483d0/sandbox
new MongoMemoryServer({binary: {downloadDir: sandboxPath}}})
```

But I get this error:
```
Error: EROFS: read-only file system, open '/home/flolu/.cache/bazel/_bazel_flolu/7213acaffdabec4878e1d1fe276483d0/sandbox/4.0.14.lock'
```

**Comment by thesayyn** [comment]
What do you get when you remove the sandbox segment as well? If it does not work as well, you can just use the global cache directory of the operating system.

**Comment by flolu** [comment]
@thesayyn I've tried all three paths, but it's always `Error: EROFS: read-only file system`

**Comment by thesayyn** [comment]
Maybe you can use the OS cache path. It might something related to the linux sandbox.
