### ISSUE TITLE
Port to linux/arm64

### ISSUE THREAD

**Issue by vielmetti** [bazelbuild/rules_nodejs#231]
Support arm64 in these builds. There's a fully supported Node.JS for arm64, but Bazel doesn't know how to fetch the right images.

At minimum this is changes at https://github.com/bazelbuild/rules_nodejs/blob/master/internal/common/os_name.bzl#L28 plus pointers to the right Node.JS images in https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node/node_repositories.bzl

**Comment by alexeagle** [comment]
We also allow you to point to your own nodejs or even vendor it in your repo - does one of those options work for you?

**Comment by vielmetti** [comment]
@alexeagle - the goal for arm64 support is full parity with other platforms to allow completely automated build enviornments. Patching and vendoring etc do not accomplish that goal.

**Comment by alexeagle** [comment]
Sorry this has gone a while with no reply.

Why does vendoring arm64 version of node into the repo not solve the problem? You'd check in the copy of node you want to use and bazel in your build environment would call it. Is it because you also want to use the binaries for the other platforms in the same build?

**Comment by photex** [comment]
Just skimming issues as I start to tread water with bazel here; but I thought I'd chime in to say it's my goal to be able to use bazel to cross-compile native node modules for aarch64 in addition to having modules built on the host architecture which is x86_64. 
We have embedded systems components and desktop components and while it's largely C, there are Python and Node tools and libraries that need to be built for one or both architecture.

**Comment by enriched** [comment]
Chiming in here as well, it seems like support for this kind of use case is supposed to be coming in September based on the [Bazel Configurability Roadmap](https://bazel.build/roadmaps/configuration.html). Or maybe they are working on it this month based on the `User-Defined Configuration` section.  Does rules_nodejs already support these kinds of options?

My current situation is on a mac:
```
[typescript] -> [javascript] -> [Docker image] -> [Local k8s]
```
with some external npm modules sprinkled throughout. Unfortunately the `node_image` rule from [rules_docker](https://github.com/bazelbuild/rules_docker) doesn't work for me because it's adding in the `@nodejs//:node` binary and when you're running the build locally it will not run in the `gcr.io/google-appengine/debian9` image.

**Comment by Toxicable** [comment]
https://github.com/bazelbuild/rules_nodejs/pull/645 would solve this

**Comment by alexeagle** [comment]
Since we have toolchain support now maybe this is easy to solve? Could use someone trying it out

**Comment by vielmetti** [comment]
Hi @alexeagle Are you referring to the support merged in with https://github.com/bazelbuild/rules_nodejs/pull/898 ? If so perhaps this is more straightforward to address than previously, though 898 does not include any arm64 support it would appear to provide a framework for adding same.

**Comment by Toxicable** [comment]
@vielmetti yup exactly

**Comment by kgreenek** [comment]
I have a need for this. We build on the nvidia xavier platform, which is aarch64.

The challenging part of this is that there currently isn't a way to determine the system architecture in the workspace context.

**Comment by kgreenek** [comment]
It is possible to get the host architecture in a repository_rule, with a line like this:
```
arch = repository_ctx.execute(["uname", "-m"]).stdout.strip()
```

That could be added to the node_repositories_rule impl in internal/node/node_repositories.bzl. I am going to take a stab at that, and see how it goes.

**Comment by alexeagle** [comment]
thanks @kgreenek - do you have an idea if any more changes are needed to close this issue?

I imagine we should have some CI testing on arm64 but I dunno where we would run that, and at least right now I don't think there's a surface for arm-only bugs?

**Comment by kgreenek** [comment]
I think it's probably safe to call this "complete". I am able to depend on nodejs rules and use them on aarch64 without problems (in my initial testing at least). I am currently using it for the grpc ts_proto_library rule in labs fwiw, but I expect the other rules should work fine too, and I'll likely being using more of those soon.

If you build this repo itself (instead of using it as an external dependency from another workspace), bazel fails when loading the workspace because io_bazel_rules_webtesting doesn't support aarch64. Setting up CI for aarch64 is going to be tricky. As far as I know, you can't disable stuff in the WORKSPACE file conditionally based on arch. That means you'd either need to update the webtesting rules upstream, or conditionally disable the webtesting rules it by generating your WORKSPACE file using a configure script. Tensorflow does that. There might be a better work-around though.

**Comment by alexeagle** [comment]
great, I agree we can close this one.
It seems like the main problem will be arm users who want to depend on rules_nodejs from source instead of our distro. If we run into that, maybe we can just drop the dependency on rules_webtesting - though it doesn't hurt to file an issue with them about the error.

Thanks again!

**Comment by kgreenek** [comment]
Thank you!
