### ISSUE TITLE
Unable to Upgrade from NgRx v9 to v10

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2320]
# Affected rules
- ts_devserver

# Reproduction
1. Clone [this](https://github.com/flolu/angular-bazel-starter) repository, specifically this commit:
https://github.com/flolu/angular-bazel-starter/tree/64f4876d7e4a59411cbd1487dd0e6260ac7ee225

2. Install dependencies
```
yarn
```

3. Upgrade to NgRx v10
```
yarn add @ngrx/store @ngrx/router-store @ngrx/entity @ngrx/effects -D @ngrx/store-devtools
```

4. Run the devserver
```
yarn client
```

In the browser console on http://localhost:4200 there is this error:
```
effects_feature_module.ngfactory.js:7

Uncaught SyntaxError: Cannot use import statement outside a module
    at ts_scripts.js?v=58118563:19381
```

Note: the problem disappears when running the production app (`yarn client:ssr`)

Might be related to #2280

**Comment by flolu** [comment]
The issue remains with NgRx v11

**Comment by flolu** [comment]
**Minimal reproduction**

To reproduce this issue follow these steps:

1. `git clone https://github.com/flolu/bazel-concatjs-ngrx-issue`
2. `cd bazel-concatjs-ngrx-issue`
3. `yarn install`
4. `yarn start` (Open http://localhost:4200, works fine)
4. `yarn upgrade-ngrx` (Upgrade NgRx to v11)
6. `yarn start` (Open http://localhost:4200, error in the browser console)

Note, that the production server `yarn prod` works fine on both versions of NgRx.

**Comment by alexeagle** [comment]
Hey @robwormald still around?

**Comment by mattem** [comment]
Answered on [SO](https://stackoverflow.com/questions/66733779/cannot-use-import-statement-outside-a-module-bazel-concatjs-ngrx/66837422#66837422). 

I'm unsure if those `ngfactory.js` should be being included in the generated `js_library` srcs ([here](https://github.com/bazelbuild/rules_nodejs/blob/c47b770a122e9614516df2e3fdca6fe0bf6e3420/internal/npm_install/generate_build_file.ts#L941)), or if they should even be part off the distribution from NgRx?

@alan-agius4 @jbedard Perhaps you know?

**Comment by alan-agius4** [comment]
`ngfactory.js` are not part of the disturbed library.

They are generated when building an application using the deprecated rendering engine (ViewEngine). With Ivy ngfactories are not longer needed. However, under Bazel generation of factories is forced, https://github.com/bazelbuild/rules_nodejs/blob/c47b770a122e9614516df2e3fdca6fe0bf6e3420/third_party/github.com/bazelbuild/rules_typescript/internal/common/tsconfig.bzl#L165:L173

I suspect the `import` is generated because of the module configuration in the tsconfig https://github.com/drakery3d/fullbazel/blob/64f4876d7e4a59411cbd1487dd0e6260ac7ee225/services/client/tsconfig.json#L6

Note: ViewEngine compilation of applications will no longer be supported in v12.

**Comment by mattem** [comment]
> ngfactory.js are not part of the disturbed library.

Are we saying they shouldn't be? This file is included with NgRx on npm, and has been since version 10. 

https://unpkg.com/browse/@ngrx/store@11.0.1/esm2015/src/store_module.ngfactory.js

Should rnj still be including these as part of the generated js_library sources though?

**Comment by alan-agius4** [comment]
Yeah, I meant, that ngfactories should be distributed. That does seem like there is an issue with the distributable of ngrx, although that being said, esm2015 is not typically used, in Bazel umds are used, while with Angular CLI FESM2015 is used.

I think they can be removed from `src`, since when needed they should be `outs` of the application built.
