### ISSUE TITLE
Docs site version shows "3.0" option but no "3.1" option, even though rules_nodesjs 3.1 has been released

### ISSUE THREAD

**Issue by pshields** [bazelbuild/rules_nodejs#2453]
# 🐞 bug report

### Affected Rule

Docs site (https://bazelbuild.github.io/rules_nodejs/)

### Description

The docs site still shows "Version: 3.0" as the version in the sidenav even though 3.1 has been released. There is no option for "Version: 3.1".

## 🔬 Minimal Reproduction

Visit https://bazelbuild.github.io/rules_nodejs/ and check the "Version: " string in the select at the top of the sidenav.

### More info

It looks like the docs site was redeployed with the latest documentation as of the 3.1 release, but the hard-coded version string in the sidenav template was not updated. I'll see if I can send a PR with the fix.

**Comment by pshields** [comment]
For some reason, when I run `yarn stardoc` locally, the generated files omit the `language-plaintext` CSS class in all of the code blocks, so the diff is much larger than it needs to be. Not sure what the purpose of that class is or why it is there, so I'm a bit stuck at the moment in terms of sending a PR.

I think the only real change that needs to be made here (aside from re-generating the static content) is replacing the two instances of "3.0" with "3.1" in `docs/_includes/sidenav.html`, and then re-generating the static content.

**Comment by pshields** [comment]
If I can figure out why my generated doc files don't contain the `language-plaintext` class, I can send a PR for this. I might have time to investigate further in the coming days. It also occurs to me that it might be nice to have a build target for generating the doc files in a reproducible manner.

**Comment by mattem** [comment]
The docs story isn't great, and it's on the list of areas we'd like to improve (versioned docs being one of the improvements).
The reproducibility issue is due to the Jekyll rule relying on a local install of Ruby and Jekyll 😞 I get the same removal of `language-plaintext` too, so I guess I have a different version to Alex when he published the docs.

There are two issues here:

- [ ] Update the current version selection to say 3.1
- [ ] Update the release scripts to either bump this automatically or add a note in the readme to update that file when releasing a minor version bump

**Comment by mattem** [comment]
Addressed the first part in #2460 with a quick find/replace and #2461 to update release instructions

**Comment by alexeagle** [comment]
actually we only plan to make separate docsites for majors right now, since it's a manual hack. so we should just change this label to `3.x`
