### ISSUE TITLE
esbuild can't resolve workspace absolute imports

### ISSUE THREAD

**Issue by shosti** [bazelbuild/rules_nodejs#2474]
# 🐞 bug report

### Affected Rules

- `ts_library`
- `esbuild`

### Is this a regression?

No.

### Description

I may be configuring something wrong, but `esbuild` can't seem to find transitive `ts_library` dependencies within the workspace.

## 🔬 Minimal Reproduction

I have a minimal reproduction at https://github.com/shosti/bazel-rulesjs-repro.  There's a top-level `ts_library` (`:a`) that includes `lib/b.ts` as a dependency (imported as `"myworkspace/lib/b"`). Running `bazel build //:a` succeeds, which indicates that the import paths are correct as far as `tsc` is concerned.

There's also an `esbuild` bundle (`:bundle`) that depends on `:a`. Running `bazel build //:bundle` fails with an import error message.

## 🔥 Exception or Error

<pre><code>
 > ../../../../../execroot/myworkspace/bazel-out/k8-fastbuild/bin/a.mjs: error: Could not resolve "myworkspace/lib/b" (mark it as external to exclude it from the bundle)
    1 │ import foo from "myworkspace/lib/b";
      ╵                 ~~~~~~~~~~~~~~~~~~~

1 error
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 20.10
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.5.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Sep 2 20:11:46 2020 (1599077506)
Build timestamp: 1599077506
Build timestamp as int: 1599077506
  </code>
</pre>

**Rules_nodejs version:** 

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.2.0
  </code>
</pre>

**Anything else relevant?**

**Comment by jbedard** [comment]
I think it's the use of the `myworkspace/` that doesn't work? I think I have other transitive deps working fine but I'm running into this workspace issue as well...

**Comment by mattem** [comment]
Yeah this `esbuild` not knowing how to resolve the absolute workspace imports, `rollup_bundle` gets this for free as it's called via `run_node`, where as `esbuild` gets called on the command line with a bunch of flags.

If we want to support this mode, then somewhere in here we could add a mapping in to the generated jsconfig:
https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/esbuild/helpers.bzl#L78

**Comment by yohcop** [comment]
I was having the same problem. I renamed all my imports and removed the workspace name, but then I had errors in `ts_library()`, since the `ts_library` setup expects imports to be under the workspace name.  It's also how it's described under [Writing TypeScript code for Bazel](https://bazelbuild.github.io/rules_nodejs/TypeScript.html#writing-typescript-code-for-bazel)

So I'd say it would need to be supported :/

As I was looking at the config, I was also wondering about generated files. Once I have a different computer I'll be able to try, but should `bazel-bin/...` or `bazel-out/...` also be included in [`rootDirs`](https://github.com/bazelbuild/rules_nodejs/blob/31912803caac029302c5db07e22fbb2aacec68cb/packages/esbuild/helpers.bzl#L102) ?
