### ISSUE TITLE
Cannot use filegroup for srcs in ts_project

### ISSUE THREAD

**Issue by tbezman** [bazelbuild/rules_nodejs#2504]
# 🐞 bug report

### Affected Rule

ts_project

### Is this a regression?

I don't think so

### Description

When using `srcs` in `ts_project`, using a filegroup causes the rule to be unable to find any TypeScript files. I'm pretty sure this is because `ts_project_macro` passes along sources to `_out_paths` which does not expand the filegroup. 

https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/internal/ts_project.bzl#L668

## 🔬 Minimal Reproduction

I've created a minimum repro in this repo https://github.com/tbezman/ts-project-repro . Note the comments over here https://github.com/tbezman/ts-project-repro/blob/master/some-package/BUILD.bazel#L18

## 🔥 Exception or Error

<pre><code>
ERROR: Traceback (most recent call last):
        File "/Users/terencebezman/Code/ts-project-repro/some-package/BUILD.bazel", line 15, column 11, in <toplevel>
                ts_project(
        File "/private/var/tmp/_bazel_terencebezman/d9e2260f83532a6e2ac3b769af8ce672/external/npm/@bazel/typescript/internal/ts_project.bzl", line 663, column 13, in ts_project_macro
                fail("""ts_project target "//{}:{}" is configured to produce no outputs.
Error in fail: ts_project target "//some-package:the_project" is configured to produce no outputs.

Note that ts_project must know the srcs in advance in order to predeclare the outputs.
Check the srcs attribute to see that some .ts files are present (or .js files with allow_js=True).
ERROR: Skipping '//some-package:the_project': no such target '//some-package:the_project': target 'the_project' not declared in package 'some-package' defined by /Users/terencebezman/Code/ts-project-repro/some-package/BUILD.bazel
WARNING: Target pattern parsing failed.
ERROR: no such target '//some-package:the_project': target 'the_project' not declared in package 'some-package' defined by /Users/terencebezman/Code/ts-project-repro/some-package/BUILD.bazel
INFO: Elapsed time: 0.138s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
</code></pre>

## 🌍  Your Environment

**Operating System: MacOS Big Sur**

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: development
Build label: 4.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:38:50 2021 (1611214730)
Build timestamp: 1611214730
Build timestamp as int: 1611214730
  </code>
</pre>

**Rules_nodejs version:  3.2.1**

**Anything else relevant?**

**Comment by alexeagle** [comment]
Yeah this is not currently possible because we need to predict the output paths of the .js files.

Is there a reason you use filegroup here, rather than
```
_SRCS = glob(
    include = ["src/**/*.ts"],
)
ts_project(srcs = _SRCS)
```
?

**Comment by tbezman** [comment]
@alexeagle The reason is more we already had a filegroup so we wanted to re-use that. Feels weird to have both the filegroup and the glob available for an engineer to use.

**Comment by tbezman** [comment]
@alexeagle To get to the real reason why I even needed an extra filegroup is `ts_project` will take `include` but seems to ignore `exclude` in the `tsconfig.json`. Should I make another repo to show that off?

**Comment by tbezman** [comment]
@alexeagle I pushed up a change to the source repo removing the `srcs` attribute. Running this outside of bazel is not the issue. The issue is that `ts_project` expects to see declaration files for the test files even though my `tsconfig.json` explicitly excludes them. You can see the error here

```➜  ts-project-repro git:(master) ✗ bazel build //some-package:the_project --subcommands
INFO: Analyzed target //some-package:the_project (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
SUBCOMMAND: # //some-package:the_project [action 'Compiling TypeScript project //some-package:the_project [tsc -p some-package/tsconfig.json]', configuration: 86e57527e1c8bb10edc853e734cb858f8159d8f3e0a4df9ceb16f80aad784b93, execution platform: @local_config_platform//:host]
(cd /private/var/tmp/_bazel_terencebezman/d9e2260f83532a6e2ac3b769af8ce672/execroot/workspace && \
  exec env - \
    BAZEL_NODE_MODULES_ROOTS='' \
    COMPILATION_MODE=fastbuild \
  bazel-out/host/bin/external/npm/typescript/bin/tsc.sh --project some-package/tsconfig.json --outDir bazel-out/darwin-fastbuild/bin/some-package --rootDir some-package/src --declarationDir bazel-out/darwin-fastbuild/bin/some-package/types '--bazel_node_modules_manifest=bazel-out/darwin-fastbuild/bin/some-package/_the_project_TsProject.module_mappings.json')
ERROR: /Users/terencebezman/Code/ts-project-repro/some-package/BUILD.bazel:15:11: output 'some-package/types/add.test.d.ts' was not created
ERROR: /Users/terencebezman/Code/ts-project-repro/some-package/BUILD.bazel:15:11: Compiling TypeScript project //some-package:the_project [tsc -p some-package/tsconfig.json] failed: not all outputs were created or valid
Target //some-package:the_project failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.002s, Critical Path: 1.73s
INFO: 2 processes: 1 internal, 1 darwin-sandbox.
```

**Comment by tbezman** [comment]
After looking at the source for `ts_project`, I see it doesn't read from the `tsconfig.json` it just uses a default glob. https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/typescript/internal/ts_project.bzl#L572 . I'd be happy to make a PR to support filegroups but I'm guessing there is no way to expand the filegroup until you are inside of the rule context.

**Comment by xa4a** [comment]
I've hit the same issue but with a generated `*.ts` sources from another rule's default outputs, instead of a filegroup.

I have a [rule that compiles protobufs using protobuf-ts](https://github.com/xa4a/bazel-ts-proto/tree/ed6e6cdcce76a8594220c0c30490d4d5a9ecf6c1). The rule outputs a set of `*.ts` files as opposed to other TS protobuf compilers that do `.d.ts` + `.js`.
 
To package these `.ts` files into an npm I wanted them translated to `.d.ts`+`.js` using a `ts_project()`.

The intuitive way would be to specify the proto rule label that outputs `.ts` files as `srcs` to `ts_project()`, but due to this issue with macro not being aware of the files behind the specified label, it fails.

This works however with the generated sources that have explicit labels, like those from a `genrule` or if I change my protobuf compilation rule to accept a list output attrs that are `*.ts` files and specify those as `ts_project()` srcs

See repro: https://github.com/xa4a/bazel-ts-proto/blob/ed6e6cdcce76a8594220c0c30490d4d5a9ecf6c1/BUILD

**Comment by alexeagle** [comment]
> only solution I see working here is having ts_project use output_dir instead of specifying the outs per input file

Yes, exactly! We actually documented that here:

https://bazelbuild.github.io/rules_nodejs/TypeScript.html#alternatives
> The only reason to use raw tsc is if you want to compile an opaque directory of .ts files and cannot enumerate them to Bazel. (For example if the .ts files are generated by some tool). This will produce an opaque directory of .js file outputs, which you won’t be able to individually reference.

So if you can't enumerate the sources to the `ts_project` ahead-of-time, then just call `tsc` directly.

**Comment by twheys** [comment]
Sorry to resurrect a dead issue, but I wanted to suggest a way to implement a fix for this issue.

The reason given is that the outputs need declared for the rule. The problem here, is that this is being done in the macro, rather than inside of the rule. A solution would be to move all of the output declarations from the ts_project macro body into the ts_project bazel rule. If that is done, Bazel will resolve a list of a files that come from all of the different rules being passed into the `srcs` attr available under `ctx.files.srcs`. It would be possible to declare an output_file by iterating through the list of files.

Here's a toy example:
```
def _ts_project_impl(ctx):
    ...
    js_outs = []
    typings_outs = []
    for src in ctx.attr.srcs:
        ext_len = len(src.extension) + 1
        file_name_no_ext = src.path[:-ext_len]
        
        if src.extension == 'ts':
            js_outs.append(ctx.actions.declare_file(file_name_no_ext + ".js"))
            typings_outs.append(ctx.actions.declare_file(file_name_no_ext + ".d.ts"))
            
        if src.extension == 'tsx':
            js_outs.append(ctx.actions.declare_file(file_name_no_ext + ".jsx"))
            typings_outs.append(ctx.actions.declare_file(file_name_no_ext + ".d.ts"))
        ...
```

I think fixing this would be a nice improvement to these typescript rules because it better fits intended the design of Bazel and  also allows the typescript rules to accept srcs from other rules that yield generated files.

I'd be happy to work on a PR, just thought I would make this suggestion first to get some feedback from the maintainers before going forward with it.

I'd be happy to hear your feedback, @alexeagle

**Comment by alexeagle** [comment]
`ctx.actions.declare_file(file_name)` doesn't work because then you have no label to refer to the output. we want "pre-declared outputs" - ts_library had that defect https://github.com/bazelbuild/rules_nodejs/issues/1563
that's why the macro predicts the output files.

`ts_project(srcs=["thing.ts"])` -> you want to be able to reference `//path/to:thing.js` in a subsequent target.

With that in mind, do you have any suggestion what to do?

**Comment by twheys** [comment]
Ok, I didn't realize that this would be a side effect of not pre-declaring the outputs and I can understand why that would be an issue. However, it would be still nice if it were possible to use generated files as inputs into `ts_project`. As a possible compromise, how about we predeclare outputs when it's possible to derive them from the srcs but not fail the rule when it is not? That adds a little complexity but it would make it possible to do both. Additionally, we could accept an `outs` parameter like with `genrule` where the user can manually specify some output files that cannot be derived from the srcs?

Here's a toy example
```
filegroup(
    name="my_other_package",
    srcs=["file_from_my_other_package.js"]
)

ts_project(
    name = "my_package",
    srcs = glob(["**/*.ts"]) + [":my_other_package"],
    outs=["file_from_my_other_package.js"],
    deps = [
        "//horizon/typings",
        "@horizon_npm//:node_modules",
    ],
)
```

**Comment by alexeagle** [comment]
How would the rule know when the outputs cannot be predicted and fall back to cycle.declare_file?

We could certainly expose the existing attributes like js_out through the macro.

**Comment by twheys** [comment]
The outputs can be pre-declared in the same fashion they are now, by finding all of the `ts` and `tsx` files in the list of srcs, but if we remove [this check](https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/internal/ts_project.bzl#L697) in the macro, then the rule won't fail if it can't pre-declare outputs. 

That would mean the pre-declared outputs would be calculated as they are now, but if no pre-declared outputs can be determined, for example if a label pointing to a filegroup or some other rule that generates files, then the macro won't fail. The remaining outputs can be calculated inside the impl of the rule, where the full list of files is resolved by bazel in `ctx.files.srcs`.

If there are no outputs, the rule can fail from inside the impl, but it seems like a lot of other bazel rules do not fail if there are no outputs, so that might be something we want to consider doing here too.

BTW, this might improve some other usability as well, for example if a user wants to wrap some static `.d.ts` files with a rule that produces `DeclarationInfo` so they can be used as a dep for other `ts_project` targets. Right now, it doesn't seem like it's possible to do that without including some `ts`/`tsx` sources.

**Comment by ljharb** [comment]
bump
