### ISSUE TITLE
Cypress test rule should support `supportFile`

### ISSUE THREAD

**Issue by adam-thomas-privitar** [bazelbuild/rules_nodejs#2777]
# 🚀 feature request

### Relevant Rules

`cypress_web_test` rule.

### Description

Currently only `pluginsFile` is supported but support for the (important -- it enables custom commands in cypress) `supportFile` is missing.

More info [available on the cypress docs](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file).

### Describe the solution you'd like

We can just add the `supportFile` arg to `cypress_web_test`.

**Comment by jorunfa** [comment]
My workaround for this problem was to update the `supportFile` and `fixturesFolder` in the config, of my custom `plugin.js`.

```js
// ...
module.exports = async (_on, config) => {
    // `on` is used to hook into various events Cypress emits
    // `config` is the resolved Cypress config

    // ...
    config.supportFile = "my/project/folder/cypress-tests/cypress/support/index.js"
    config.fixturesFolder = "my/project/folder/cypress-tests/cypress/fixtures";
    
    return config;
}
```

Ref: https://docs.cypress.io/guides/references/configuration#Folders-Files

**Comment by alexeagle** [comment]
@jorunfa do you think that workaround is enough to solve the problem? I suppose it means if you give a wrong path, you get an error from cypress, where it might have been nice for Bazel to give you an error sooner.

**Comment by jorunfa** [comment]
@alexeagle, yes, it solved the problem for me. See what you mean; in my experience I had no problems with it after figuring out how I could configure the paths.

Rather than having `supportFile` (and `fixturesFolder`), and perhaps even `config_file` available as params to `cypress_web_test` I think my preferred solution would be to have support for [`--project`](https://docs.cypress.io/guides/guides/command-line#cypress-open) cli flag. I think that might provide the best "just works" solution, apart from the custom plugin needed to boot the server.

E.g.:
```bazel
load("@cypress//:index.bzl", "cypress_web_test")

cypress_web_test(
    name = "test",
    srcs = glob([
      "cypress/**/*",
      "cypress.json",
    ]),
    data = [],
    plugins_file = "bootServerPlugin.js",
    project = "my/project/cypress-tests",
)
```

**Comment by KatSick** [comment]
Hi there 👋🏻 

I do believe, that @jorunfa workaround is good, since we need to hardcode absolute folder to the support file.
I think, support for `supportFile` for `cypress_web_test` is still needed

**Comment by alexeagle** [comment]
@mrmeku want to add this on your list for cypress rule improvements?
