### ISSUE TITLE
[linker]: discussion whether link modules aspect should allow for duplicate mappings 

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#2810]
This is an issue mostly for discussion: 

With https://github.com/bazelbuild/rules_nodejs/pull/2799, the trick for ts_library linker mappings has been removed. The trick allowed for duplicate mappings where the `module_name` mapping for the linker is always overwritten by other non-tslibrary linker mappings.

Given the removal of the "trick", I wonder what the recommended way for a pattern like this is:

```
ts_library(
  name = "core",
  package_name = "@angular/core",
  srcs = [..]
)
pkg_npm(
  name = "npm_package",
  package_name = "@angular/core",
  deps = [":core"],
)
my_nodejs_test(
  name = "api-golden-test-using-npm-package",
  data = [":npm_package"]
)
```

One might argue, that I should not have a `package_name` on the `ts_library` then, but there can be cases where the workspace defines other tests that prefer the output from the source target directly? This is reasonable because assembling the NPM package is slower & may contain additional dependencies that aren't necessarily needed for tests.

At first glance while looking at the linker aspect, I'd expect the mapping from the actual aspect target to take precedence over the one on the determined from transitive `deps` et al. Are there any concerns with that?

**Comment by gregmagolan** [comment]
Interesting. I removed the trick so I could simplify the code as there was a hack in the linker to support the dual purpose module_name in ts_library. In theory, an override could be done such that a direct dependencies link name takes precedence over a transitives.

The trouble I see is that in a non-sandboxed Windows environment, only one link can live at a time so two tests that have different link definition would stomp on each other if running simultaneously. The failure mode would be flaky and error message random and not helpful. A user could run into this already since the duplicate check is only per target but the current check provides at least some level of protection.

**Comment by devversion** [comment]
Yeah, it definitely made sense to remove the trick :+1: Nice cleanup! good point with the potential flakiness for Windows. The linker causes a lot of flakiness for concurrent builds regardless of this change though (due to modifications on a single `node_modules` folder); so I'm not sure if it's helping a lot.

I'd agree with the general idea of providing some safety check here (even it's just at a target level), but at the same time I feel like this not being a strong-enough argument given that this check would only help with Windows (where the linker is not working reliably anyway unfortunately; and such errors could occur even without duplicate mappings).

The real reason why this issue surfaced in the Angular organization is that we did not specify a `package_name` on the `pkg_npm` targets, but now `validate` defaults to `True` and we'd need to set a package name. Surely we could disable the
validation but it would be also nice to keep the validation as it seems quite useful too.

**Comment by gregmagolan** [comment]
That is a good point that not allowing a feature because it doesn't work on Windows well is not a strong argument. Windows already has a lot of issues with bazel and other rule sets besides this one and there is already some flakiness with the linker even without conflicting modules.

I suppose we could detect if we are running in a sandbox in the linker and print out a warning of some sort if there are potential conflicting linked modules. Ideally a suppressible warning when the conflicting modules are intentional.

A direct dep with a conflicting link trumping transitive links could work and cover your use case it would seem. Probably needs some thought as to what the fallouts will be since a direct dep will be a transitive one for the next target in the graph.

I do think that pattern will be more flaky on Windows than the current Windows flakiness so you'd have to think about how to solve for the non-sandboxed Windows case for your developers.

@alexeagle do you have an opinion on this one?

**Comment by alexeagle** [comment]
Feels to me like we should keep brainstorming for a solution that reduces overall complexity. I think we should avoid users needing to understand even more "modes" of behavior for the linker, which to them is a foreign concept.

Looking back to first principles, I think the thing that can be "linked" should be 1:1 with something you can `npm link` and clearly two targets declaring that they are the same package doesn't work with that non-bazel idiom. So naively I think having a package_name on a ts_library is the thing to avoid here.

@devversion do you need the `package_name` on the `ts_library` just to get the named UMD modules, or do you also need the side effect of whatever the linker later does with that thing?

[I'm on vacation so responses and mental processes delayed]

**Comment by gregmagolan** [comment]
If we removed package_name entirely from ts_library, which I suppose we could for 4.x, you'd be able to achieve the same pattern with js_library after a ts_library.

However, that doesn't address the problem of wanting to have two different targets (whether they be two different js_library targets or a js_library & ts_library) with the same package_name in the same action.

But Alex does make a good point that you could restructure to
```
ts_library(
  name = "core_compile",
  package_name = "@angular/core",
  srcs = [..]
)
js_library(
  name = "core",
  package_name = "@angular/core",
  deps = [":core_compile"],
)
pkg_npm(
  name = "npm_package",
  package_name = "@angular/core",
  deps = [":core_compile"],
)
my_nodejs_test(
  name = "api-golden-test-using-npm-package",
  data = [":npm_package"]
)
```
and that should solve your use case @devversion.

**Comment by devversion** [comment]
> Looking back to first principles, I think the thing that can be "linked" should be 1:1 with something you can npm link and clearly two targets declaring that they are the same package doesn't work with that non-bazel idiom. So naively I think having a package_name on a ts_library is the thing to avoid here.

Yeah, that definitely is a good point, and this would mean that duplicate mappings should naturally result in an error. 

> and that should solve your use case @devversion.

Oh yeah, that would do it. Thanks! I'd need to see if it's worth going that route, but that would allow us enabling `validate` in the Angular org for the NPM package targets.
