### ISSUE TITLE
Performance issue with jest during startup

### ISSUE THREAD

**Issue by fa93hws** [bazelbuild/rules_nodejs#2817]
# 🐞 bug report

### Affected Rule

`Jest`

 The issue is caused by the rule: 

### Is this a regression?

No

 Yes, the previous version in which this bug was not present was: ....

### Description

Jest use `jest-haste-map` to crawl all files under working directory to build a map to boost its performance in large repository.
It takes some time but it works very well if bazel is not involved.
However, in the current bazel jest example, jest will be executed separately and hence jest need to build the haste map during the startup everytime. That adds 10s for each bazel-jest invocation.
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
N/A, only happens in large repo...

## 🔥 Exception or Error
No, just slow
<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS Catalina 10.15.7 
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
4.1.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
3.6.0
  </code>
</pre>

Jest verions: 26

**Comment by alexeagle** [comment]
This is a good problem statement. But I'm not sure there's anything we can do about it.
Apparently Jest is slow, and as a workaround, they have to run in watch mode always to avoid that slow startup penalty.

Bazel doesn't keep test runners alive in the background, as you observe it always starts the test process for each execution. So we need Jest to be faster without having to use its watch mode.

(Generally there's a big mismatch running Jest under Bazel because Jest expects to be the entire build system on it's own, not be layered underneath another one. As another example, Jest will always try to shard tests across all the CPUs on the machine, but this is also Bazel's job)

@mrmeku any thoughts on this? You've contributed to jest-haste-map.

(FWIW I'm currently slogging in a terrible 30sec jest_test loop right now so I'd love to fix this too, I just don't see how rules_nodejs can do anything...)

**Comment by mrmeku** [comment]
@alexeagle The way jest haste map works, it creates a cache directory for its transpiled code and tried not to recalculate transpilations to the best of its ability. I believe part of the problem here is that bazel's sandboxing does not allow jest to reuse this cache directory (though I do need to validate that statement)

One way to increase the speed without caching is to use a faster transpiler like swc or esbuild

Otherwise, transpilation could be done in a pre test build step and utilize a worker which can utilize a cache

Or we can figure out how to make jest tests non hermetic and accept the fact a cache will be used

Not proposing a solution right now, just wanted to write down my thoughts for discussion

**Comment by lencioni** [comment]
If it is helpful, here is where Jest added the custom haste option: https://github.com/facebook/jest/pull/11107
