### ISSUE TITLE
Find a way to reuse the `tsbuildinfo` files on `ts_project` rule

### ISSUE THREAD

**Issue by mistic** [bazelbuild/rules_nodejs#2850]
Continues https://github.com/bazelbuild/rules_nodejs/issues/1726

I had a quick conversation with @alexeagle and we think we need a way to make the typescript compilations at least so performant as they are with typescript outside bazel today without the express requirement of using a worker to achieve that. 

I plan to start an experimentation with it and will update the issue accordingly.

**Comment by alexeagle** [comment]
@pauldraper is this still an area you're interested in? I heard you were working on an alternative implementation for Bazel/TS, did you make progress on that?

Since the .tsbuildinfo file is both an output from a compilation as well as an input to a subsequent one, we might still need a persistent worker under Bazel just to keep track of that file, as you pointed to in rules_scala https://github.com/higherkindness/rules_scala/blob/master/docs/stateful.md#stateful-compilation

This will lead to solving the same problem we have for existing workers: we currently need to setup the node_modules links when launching the nodejs process, but the needed third-party libraries differ for each WorkRequest.

We've been over this many times in the past, but since @mistic is interested in taking a deeper dive here maybe now is the time to revisit the discussions and look for more options.
