### ISSUE TITLE
add example demonstrating vendored npm/yarn

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#289]
and these are probably broken, the rule needs to use a label to reference them now that we are RBE-compatible

**Comment by lexor90** [comment]
In order to get the checked-in YARN to work I had to make some small changes, specifically:

1. Define in my WORKSPACE 

 ```python
node_repositories(
  # ... other settings ...

  # __workspace_dir__ is needed as this expects an absolute path.
  # Maybe a Label would be fine here, but first check https://github.com/bazelbuild/bazel/issues/3901
  yarn_path = __workspace_dir__ + "/third_party/nodejs/github.com/yarnpkg/releases/tag/v1.9.3"
)
```

2. Add a symlink in `node_repositories.bzl` pointing to the user-defined path

```diff
diff --git a/redacted/rules_nodejs/internal/node/node_repositories.bzl b/redacted/rules_nodejs/internal/node/node_repositories.bzl
index 87d7105c0..2dadb428a 100644
--- a/redacted/rules_nodejs/internal/node/node_repositories.bzl
+++ b/redacted/rules_nodejs/internal/node/node_repositories.bzl
@@ -121,6 +121,7 @@ def _download_yarn(repository_ctx):
     repository_ctx: The repository rule context
   """
   if repository_ctx.attr.yarn_path != "":
+    repository_ctx.symlink(repository_ctx.attr.yarn_path, YARN_DIR)
     return
 
   yarn_version = repository_ctx.attr.yarn_version
```

Without the #2 the setup would just skip the download, but then the yarn source code would not be available at the statically defined `YARN_DIR`.

I guess the same should be applied to any other override since the logic is pretty similar.

Maybe a label would be more convenient for these attributes in order to be able to resolve the absolute path without having the developer to use the `__workspace_dir__`. But I'm not sure this is a good practice (https://docs.bazel.build/versions/master/build-ref.html#label_directory). Also, note that single Labels may need a bit of extra work to resolve (https://github.com/bazelbuild/bazel/issues/3901).

If this sounds good or if you share any thought I could help with a PR for this.

**Comment by gregmagolan** [comment]
Example added to `examples/vendored_node` but it currently downloads the node & yarn distros in the example instead of having them checked in because of https://github.com/bazelbuild/rules_nodejs/issues/368
