### ISSUE TITLE
Future plans of the concatjs devserver

### ISSUE THREAD

**Issue by devversion** [bazelbuild/rules_nodejs#2904]
Hey team,

this is more of a question than an issue, but I wanted to check on the maintenance of the `concatjs` devserver that
is shipped as part of `@bazel/concatjs`.

Previously, when the devserver still was part of `rules_typescript`, it was extremely difficult to land changes (like the windows support in the past) because the devserver implementation was synced into g3 and the team was hesitant to make any changes.

Given that the TypeScript rules are now vendored, I wonder how/if the devserver is considered being maintained by `rules_nodejs`, especially since support for new platforms has been added in the past to `rules_nodejs`, but corresponding devserver binaries for these platforms have not been shipped. i.e. darwin arm64 for M1, linux_s390x, powerpc etc.

https://github.com/bazelbuild/rules_nodejs/blob/9b454e38f7e2bbc64f75ee9a7dcb6ff45f1c7a12/packages/concatjs/devserver/BUILD.bazel#L58-L78

The filegroups have been defined for these platforms supported in `rules_nodejs`, but the actual binaries for example are not built in the vendored `rules_typescript` repository.. so there is actually no support for the concatjs devserver.

It's worth asking the question: is it worth continuing to maintain the Go-based concatjs devserver, or would a more JS-based devserver be suitable (like we have built in the angular/components repo)? Such devservers could use e.g. `browser-sync` under the hood and allow for a lot of additional benefits.

**Comment by alexeagle** [comment]
answers at a couple different levels:

1. I just found that not only are we limited to the three platforms, but we're also publishing the devserver binaries in both `@bazel/typescript` and `@bazel/concatjs` so that's wasting a lot of bytes. The correct fix, which I'll work on now, is to publish the concatjs go binaries on our github releases page and not in the npm packages. Then add a toolchain definition to fetch them like we have for esbuild and cypress. Adding the missing platform binaries is then trivial. This should be in 4.1
2. Long-term we would love to drop concatjs support from rules_nodejs to reduce our scope and OSS maintenance burden. I'm just not sure where that would go, and who would support it. I don't want to leave users stranded. rules_closure is the place where Google-style JS lives but I imagine it's unlikely they would take it. Some answer for this on the 5.0 release would be nice
3. Using some JS-based devserver sounds great, but that certainly wouldn't go in rules_nodejs to begin with, so I don't have much to say :)

**Comment by alexeagle** [comment]
I'm going to need some help to get this over the finish line.

**Comment by devversion** [comment]
Agreed 👍 I've replied on the toolchain start PR you created.

> Using some JS-based devserver sounds great, but that certainly wouldn't go in rules_nodejs to begin with, so I don't have much to say :)

I'd argue that a devserver provided here would make sense because setting up devservers for Bazel w/ NodeJS requires logic for runfile resolution, so having one here seems useful. Surely this could be maintained by a third party but worth considering a simple JS based one. I don't feel strongly though.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs which only supplies the Node.js toolchain as of [v6.0.0](https://github.com/bazelbuild/rules_nodejs/releases/tag/v6.0.0-beta0).

Downstream canonical JavaScript + Node.js ruleset is now https://github.com/aspect-build/rules_js.
