### ISSUE TITLE
`concatjs_devserver` fails to find external static files on windows

### ISSUE THREAD

**Issue by zaucy** [bazelbuild/rules_nodejs#2978]
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `concatjs_devserver`

### Is this a regression?

 I'm unsure

### Description

External files in `static_files` cannot be accessed on windows.

## 🔬 Minimal Reproduction

https://github.com/zaucy/concatjs-windows-bug

## 🔥 Exception or Error

```
http://localhost:5432/npm/node_modules/@bazel/concatjs/LICENSE 404 (Not Found)
```

## 🌍  Your Environment

**Operating System:**

```
Windows 10
```

**Output of `bazel version`:**

```
Bazelisk version: v1.10.1
Build label: 4.2.1
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Aug 30 15:19:20 2021 (1630336760)
Build timestamp: 1630336760
Build timestamp as int: 1630336760
```

**Rules_nodejs version:**

```
4.2.0
```

## Workaround

I have been able to workaround this by enabling `--legacy_external_runfiles` on windows and adding `external` as an additional root path.

BUILD file from minimal Reproduction
```python
concatjs_devserver(
    name = "devserver_workaround",
    additional_root_paths = ["external"], # <- external to workaround concatjs_devserver on windows
    entry_module = "concatjs_windows_bug/main.js",
    scripts = [],
    static_files = [
        "test.txt",
        "nested/test.txt",
        "@npm//:node_modules/@bazel/concatjs/LICENSE",
    ],
    deps = ["main.js"],
)
```

`.bazelrc` from minimal reproduction

```yaml
build --enable_platform_specific_config

build --enable_runfiles
startup --windows_enable_symlinks

# On windows in order for the devserver to work we have to enable legacy 
# external runfiles
build:windows --legacy_external_runfiles
build:linux --nolegacy_external_runfiles
build:macos --nolegacy_external_runfiles
```

**Comment by alexeagle** [comment]
Probably a bug. My recent change is right in the spot where this would happen
https://github.com/bazelbuild/rules_nodejs/commit/148c85b4ddc6d480f0cf4da495f0d40267d23bf2#diff-328cd507197092ce0aa585ec68acca1084a81503fb76768f32002dcce01f0c42R13
It was a kludgey fix because a breaking change in rules_go from a couple years ago required some thoughtful rewrite but we don't have enough resources to maintain all the code.
Do you think you could dig into it a bit? If you can get to the point of building the go_binary there for Windows, you can stitch it to your concatjs_devserver with the devserver attribute.
