### ISSUE TITLE
Incorrect source paths in generated map [ts_project]

### ISSUE THREAD

**Issue by xnerhu** [bazelbuild/rules_nodejs#3003]
# 🐞 bug report

### Affected Rule

```
ts_project
```

### Description

Typescript compiler generates a map that contains paths to original source files. In run mode these paths are the same as in build mode. 

Source map from `bazel build`

```js
{
  "version": 3,
  "file": "index.js",
  "sourceRoot": "",
  "sources": [
    "../../../../../../common/utils/src/index.ts"
  ],
  "names": [],
  "mappings": ";;;;;;;;;;;;AAAA,2CAAyB;AACzB,2CAAyB"
}
```

And source map from `bazel run`
```js
{
  "version": 3,
  "file": "index.js",
  "sourceRoot": "",
  "sources": [
    "../../../../../../common/utils/src/index.ts"
  ],
  "names": [],
  "mappings": ";;;;;;;;;;;;AAAA,2CAAyB;AACzB,2CAAyB"
}
```

They are the same. But the one from `bazel run` is located in a different directory, which breaks `sources`.

```
bazel-out
  x64_windows-fastbuild
    bin
      common    <-----------------------------------------------------------------------|
        utils                                                                           |
          src                                                                           |
            index.js.map ✅ ../../../../../../common/utils/src/index.ts                |
          test.bat.runfiles                                                             |
            init                                                                        |
              common                                                                    |
                utils                                                                   |
                  src                                                                   |
                    index.js.map ❌ ../../../../../../common/utils/src/index.ts   --->  |

common
  utils
    src
      index.ts

```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 11
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Bazelisk version: v1.10.1
Build label: 4.2.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Aug 18 12:53:48 2021 (1629291228)
Build timestamp: 1629291228
Build timestamp as int: 1629291228
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
4.3.0
  </code>
</pre>

**Comment by alexeagle** [comment]
yes this is a general symptom of relative sourcemapping being unstable.

if you even `cp foo.js subdir/` then you are now responsible for repairing broken sourcemap links inside the file.

When typescript saw the files, it had `--outDir=bazel-out/arch/bin/path/to/thing` so the only "correct" way to use the result is in this same tree. even using the vanity symlink `bazel-bin/path/to/thing` means there are two fewer path segments from the js file back to the ts file, and the relative sourcemap doesn't work.

I think the best option, given that Bazel programs tend to relocate files around, is to use inline sourcemaps.
Any other fix is very brittle since you'd need to either present the files to typescript as being in different directories, or repair sourcemaps any time you copy files.

**Comment by alexeagle** [comment]
just a note that https://github.com/aspect-build/rules_ts/ doesn't have this problem, because it runs `tsc` with the working directory inside `bazel-bin` so the sourcemap paths are what you expect.
