### ISSUE TITLE
[Proposal] Install `node_modules` with a lazy-loading algorithm

### ISSUE THREAD

**Issue by ronilichtman** [bazelbuild/rules_nodejs#3262]
# 🚀 feature request

### Relevant Rules

WORKSPACE rules:

1. `yarn_install`
2. `npm_install`

### Description

Rather than calling `npm install` or `yarn install` on every `bazel` invocation in the repo, wait until a `nodejs` target is used. This is especially helpful in multilanguage monorepos in which many developers rarely touch javascript code (and don't need to wait for `npm install`).

### Describe the solution you'd like

Lazy loading of node_modules.

### Describe alternatives you've considered

Manually commenting out relevant WORKSPACE config when not working on frontend code.

**Comment by alexeagle** [comment]
This is already the behavior. If you `bazel build //package_a:all` and there are no `load()` statements from npm repositories in that package, packages it transitively loads from, or any npm repository load()ed in the WORKSPACE, then no npm fetch happens.

So really the issue here is that you have something triggering an eager fetch which is undesirable.
https://github.com/bazelbuild/rules_nodejs/issues/3193 is one example of how this can happen.
It's pretty common that such eager fetches are accidentally introduced to a codebase, and I haven't yet put together a good pattern of how to write an automated test to assert you don't do that. Would be a good blog post...

If you can isolate what `load` statement is causing the undesirable fetching, I can give more suggestions which of these to do:
- move code around to isolate the JS parts in a separate package
- make load statements lazy by loading from somewhere else

**Comment by ronilichtman** [comment]
Thanks for the quick response Alex! I managed to isolate this to the following lines in our `WORKSPACE` file:

```
load("@npm//@bazel/labs:package.bzl", "npm_bazel_labs_dependencies")

npm_bazel_labs_dependencies()
```

As long as they are there, than any simple `bazel query //my/target` calls `npm install`. I'm guessing we would need some alternative to the `npm_bazel_labs` dependency (which we are currently using for the `ts_proto_library` rule).

**Comment by alexeagle** [comment]
the simple solution is to expand that function in-place rather than load it from `@npm`.

https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/labs/package.bzl#L7 is the implementation (you're the last committer there too :)

however in 5.0 we dropped the `@bazel/labs` package, so you should probably shop around for another way to do this, like with `rules_proto_grpc`. We're working on some high-level documentation for bazel + proto/grpc at https://aaliddell.github.io/SIG-rules-authors/proto-grpc but I dunno if that's helpful here.

**Comment by ronilichtman** [comment]
Expanding in place worked perfectly! Thanks!

For posterity this is the resulting source code on our end:

1. `build/npm_bazel_labs.bzl`:
    ```starlark
# This is a copy of the following files from the bazelbuild/rules_nodejs repo:
# 1. https://github.com/bazelbuild/rules_nodejs/blob/4.4.0/packages/labs/mock_io_bazel_rules_closure.bzl
# 2. https://github.com/bazelbuild/rules_nodejs/blob/4.4.0/packages/labs/package.bzl
# 
# This is done to avoid a full "yarn install" operation in the Bazel analysis phase. This allows us to develop backend
# code without requiring a full "node_modules" directory.
# For more information, see: https://github.com/bazelbuild/rules_nodejs/issues/3262.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

def mock_io_bazel_rules_closure_impl(repository_ctx):
    repository_ctx.file(
        "closure/BUILD.bazel",
        content = """\
package(default_visibility = ["//visibility:public"])
exports_files(["defs.bzl"])
""",
    )
    repository_ctx.file(
        "closure/defs.bzl",
        content = """\
"Minimal implementation to make loading phase succeed"
def noop(**kwargs):
    pass
closure_js_binary = noop
closure_js_library = noop
closure_js_test = noop
""",
    )

mock_io_bazel_rules_closure = repository_rule(
    mock_io_bazel_rules_closure_impl,
)

def npm_bazel_labs_dependencies():
    """
    Fetch our transitive dependencies.
    If the user wants to get a different version of these, they can just fetch it
    from their WORKSPACE before calling this function, or not call this function at all.
    """

    _maybe(
        http_archive,
        name = "com_github_grpc_grpc_web",
        sha256 = "8d9b1e9b839a5254aa79cb4068b05fdb6e1de5637c1b8551f95144159a4801f2",
        strip_prefix = "grpc-web-1.2.0",
        urls = [
            "https://github.com/grpc/grpc-web/archive/1.2.0.tar.gz",
        ],
    )

    _maybe(
        http_archive,
        name = "rules_proto",
        sha256 = "66bfdf8782796239d3875d37e7de19b1d94301e8972b3cbd2446b332429b4df1",
        strip_prefix = "rules_proto-4.0.0",
        urls = [
            "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0.tar.gz",
            "https://github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0.tar.gz",
        ],
    )

    _maybe(
        mock_io_bazel_rules_closure,
        name = "io_bazel_rules_closure",
    )

    yarn_install(
        name = "build_bazel_rules_typescript_grpc_web_compiletime_deps",
        package_json = Label("//packages/labs/grpc_web:package.json"),
        yarn_lock = Label("//packages/labs/grpc_web:yarn.lock"),
        # Do not symlink node_modules as when used in downstream repos we should not create
        # node_modules folders in the external repository. This is
        # not supported by managed_directories.
        symlink_node_modules = False,
    )

def _maybe(repo_rule, name, **kwargs):
    if name not in native.existing_rules():
        repo_rule(name = name, **kwargs)
    ```
1. `WORKSPACE`:

    ```starlark
...
load("@build_bazel_rules_nodejs//:index.bzl", "yarn_install")

yarn_install(
    # Name this npm so that Bazel Label references look like @npm//package
    name = "npm",
    package_json = "//web/app:package.json",
    quiet = False,
    yarn_lock = "//web/app:yarn.lock",
)

load("//build:npm_bazel_labs.bzl", "npm_bazel_labs_dependencies")

npm_bazel_labs_dependencies()
...
    ```
