### ISSUE TITLE
Support for Nodemon or BabelNode

### ISSUE THREAD

**Issue by elrapha** [bazelbuild/rules_nodejs#330]
Is there currently support for nodemon and/or babel ?

**Comment by Globegitter** [comment]
@elrapha instead of nodemon one can just use [bazel-watcher](https://github.com/bazelbuild/bazel-watcher) and for babel support there is an in-progress PR #217 
It still needs a few things ironed out but depending on the use-case could already be used / tested. Hopefully I will get around to it again in the coming days to iron out the remaining issues.
