### ISSUE TITLE
Wrong nodejs path on windows

### ISSUE THREAD

**Issue by flemminglundahl** [bazelbuild/rules_nodejs#3399]
# 🐞 bug report

### Affected Rule

rules_nodejs

### Is this a regression?

Don't know. This is the first time we use nodejs like this.

### Description

build_bazel_rules_nodejs throws an error on windows when running _yarn_install_impl.

## 🔬 Minimal Reproduction

Initialitze nodejs as done below.

<pre><code>
http_archive(
    name = "vendored_node_windows_amd64",
    build_file_content = """exports_files(["node.exe"])""",
    sha256 = "2883e83ac3b1e1cb9a9bf65554043640849b39e86761e7c7ac50b664f42f20ff",
    strip_prefix = "node-v14.18.0-win-x64",
    urls = ["https://nodejs.org/dist/v14.18.0/node-v14.18.0-win-x64.zip"],
)

yarn_install(
    name = "npm",
    exports_directories_only = False,
    node_repository = "vendored_node",
    package_json = "//:package.json",
    yarn = "@vendored_yarn_1_22_0//:bin/yarn.js",
    yarn_lock = "//:yarn.lock",
)
</code></pre>

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/17703575/162442492-60025abd-f2b4-4a58-8d8e-8e8985521307.png)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Windows 10
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
5.0.0
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
5.3.1
  </code>
</pre>

**Anything else relevant?**
Patch has been created as a workaround: [0001-fix-wrong-nodejs-path-on-windows.zip](https://github.com/bazelbuild/rules_nodejs/files/8452097/0001-fix-wrong-nodejs-path-on-windows.zip)

I intend to create a PR with my patch changes.

**Comment by davschne** [comment]
I'm running into the same problem. I'm curious to know why the Node executable is expected to be `bin/node.cmd` when every Node package for Windows I've seen has the executable as `node.exe` (in the root directory). I assume it's an error, but I wonder if it's working as-is for anyone and if making the correction will break their code.

@flemminglundahl , thanks for the patch! Any plans to submit the PR soon? If not, do you mind if I submit it? I'd like to start using `rules_nodejs` as soon as possible, but this issue is blocking me.

**Comment by davschne** [comment]
Cool; will do. Patch seemed to work for me. Is there more to the issue?
