### ISSUE TITLE
Help: How to get coverage report from `jasmine_node_test`?

### ISSUE THREAD

**Issue by mgred** [bazelbuild/rules_nodejs#3408]
I'm trying to understand how coverage for `jasmine_node_test` (and maybe also `nodejs_test`) works. :exploding_head: 

When running `bazel coverage //...` in [`e2e/coverage`](https://github.com/bazelbuild/rules_nodejs/tree/stable/e2e/coverage), `bazel` produces a proper LCOV report.

<details>
<summary>LCOV-Report</summary>

```lcov
TN:
SF:coverage_source.ts
FN:1,isString
FNF:1
FNH:1
FNDA:2,isString
DA:1,2
DA:2,2
DA:3,1
DA:4,1
DA:5,1
DA:6,1
DA:7,2
LF:7
LH:7
BRDA:1,0,0,2
BRDA:2,1,0,1
BRF:2
BRH:2
end_of_record
```

</details>

The same works in [`e2e/typescript`](https://github.com/bazelbuild/rules_nodejs/tree/stable/e2e/typescript). However, running `bazel coverage //...` in [`e2e/jasmine`](https://github.com/bazelbuild/rules_nodejs/tree/stable/e2e/jasmine) does **not** produce any coverage report.

I tried to reporduce it with a minimal [setup](https://github.com/mgred/test_coverage) created with `yarn create @bazel ...`. Unfortunatly, there is no report after running `bazel coverage //...` :confused: and I don't really understand why? Even more confusing is, that in this example when omitting [`@npm//c8`](https://github.com/mgred/test_coverage/blob/main/BUILD.bazel#L15) as a dependency, the test rule throws an error: `c8 npm package is required for bazel coverage`, which is obvious, because the [`lcov_merger.ts`](https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/coverage/lcov_merger.ts) uses `c8`. In the *working* examples from the `rules_nodejs` repository mentioned above, however `c8` is not even included in the respective `package.json` nor a dependecy of the rule :upside_down_face: 

`bazel version` in all tried examples:

```bash
Bazelisk version: v1.11.0
Build label: 5.1.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 8 15:49:48 2022 (1649432988)
Build timestamp: 1649432988
Build timestamp as int: 1649432988
```

Thanks for any help on this :heart:

**Comment by Toxicable** [comment]
I would guess that this isn't working becuse your source file is JS without a rule to provide the `instrumented_files_info` aspect to the coverage merger.
You can see  this done for TS here https://github.com/bazelbuild/rules_nodejs/blob/stable/nodejs/private/ts_project.bzl#L205. So with the same setup in your repo, if you changed to TS as a test, you should get a coverage report, remmeber you also need `--combined_report=lcov`
Assuming this test passes, the solution here for you would be to get `coverage_common.instrumented_files_info` added to a rule which wraps your source .js files, perhaps js_library is the palce for this, however, I'm not certain since i've never used this rule, if you got the time to experiment, I'd like to see if that would work

**Comment by mgred** [comment]
@Toxicable thanks so much for this. That was the missing bit to make it work for me. :tada: 

It's worth to note that also _Source Maps_ need to be enabled, so the coverage reporter can map back to the original source file (instead of the transpiled js file)

```json
{
  "compilerOptions": {                                               
    "types": ["jasmine"],
    "skipLibCheck": true,
    "inlineSourceMap": true, 
    "inlineSources": true
  },
  "exclude": ["external/*"]
}
```

I did not try to make it work with JS, since I only use TS at the moment.
