### ISSUE TITLE
Consider pruning unused .d.ts files pulled in from transitive dependencies in ts_project

### ISSUE THREAD

**Issue by amybzhao** [bazelbuild/rules_nodejs#3449]
# 🚀 feature request

### Relevant Rules

ts_project

### Description

Hi! From my reading of the ts_project rule's implementation, it seems like the .d.ts files that are included in the DeclarationInfo provider are all of the current project's .d.ts files as well as all of their dependencies' .d.ts files. This means at each step in your dependency chain, the # of .d.ts file that are being forwarded along and serving as inputs into subsequent tsc actions can increase quickly and include .d.ts files from transitive deps that the tsc action doesn't actually need. 

**Example scenario** (lmk if I'm misunderstanding how ts_project works):
if `form/BUILD` contains:
```
ts_project(
     name = "form",
     srcs = glob(["*.ts"]),
     deps = [
          //common_components/button,
          ...
     ]
)
```
and `common_components/button/BUILD` contains:
```
ts_project(
     name = "button",
     srcs = glob(["*.ts"]),
     deps = [
          //common_components/utils,
          ...
     ]
)
```
and `common_components/utils` contains 10 TS files that each produce a separate .d.ts file, then changes to the interface of any of those 10 TS files will trigger `//form` to rebuild even if `//button` (and thus transitively `//form`) only depends on 1 of the 10 files. It also seems like all 10 .d.ts files from `common_components/utils` [will be passed along](https://github.com/bazelbuild/rules_nodejs/blob/e4842c13c0ea16af1eb620c069d7e9116f566a1a/nodejs/private/providers/declaration_info.bzl#L48-L58) in `//button`'s DeclarationInfo.

This can bloat the size of the sandbox by pulling in excess files and can cause excessive rebuilds that significantly slow down building large projects. This is one of the blockers to our company (Asana) moving to rules_nodejs's `ts_project` rule in favor of our custom rule.

### Describe the solution you'd like

We don't have a specific solution that we think is the right one necessarily, but I'll share what our custom rule does internally:

- Our rule's "compile" action has these steps (note: we're using the --outDir flag):
  1. dedupe the .d.ts files that are being passed in as dependencies/transitive dependencies
  2. run tsc with the src files + deduped .d.ts files
  3. move all of the outputted .d.ts files + dependencies' .d.ts files into a declared directory
  4. read and follow the imports of the src files and prune the .d.ts files in the declared directory down to the minimal set needed
  5. return this declared directory in a provider

Using this approach, if one of the 10 files in `//common_components/utils` changed, `//common_components/button` would still rebuild, but any .d.ts files from `//common_components/utils` that are not used in the .d.ts of `//common_components/button` will be pruned out in step 4, so changes in irrelevant utils files won't cause the build to propagate to `//form`.

### Describe alternatives you've considered

We chatted with Airbnb and they seemed to have something custom in their rules that serves a similar purpose (although with a different goal of trying to make remote execution performant). They use tsc's `--list-files` option to determine the minimal set of files required for running tsc on a given project and use that to determine what to include in a tar ball sent to remote machines.

Curious if you think something like this is something that rules_nodejs's ts_project rule might one day support! Thanks again for all the work y'all do on rules_nodejs!

**Comment by alexeagle** [comment]
Thanks for writing this up! You're right that TypeScript's compilation model requires transitive .d.ts files to be available to the type-checker, and while it's common that the vast majority are not used, I don't know of anything provided by the TypeScript team that mitigates that.

I imagine we can reproduce the same issue outside of Bazel, using typescript's [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) to execute a build over a dependency graph of multiple TS projects. So this is really a TypeScript issue, not a Bazel issue.

> read and follow the imports of the src files and prune the .d.ts files in the declared directory down to the minimal set needed

When I worked at Google we had similar issues, @evmar has a great writeup at http://neugierig.org/software/blog/2020/10/scaling-typescript.html. 

> something that rules_nodejs's ts_project rule might one day support

Of course Google, Airbnb and others have engineering resources to apply, but rules_nodejs has no funding and no contributions from Google in the last few years.
As a result, our basic design principle in this repo and with `ts_project` is to avoid writing or maintaining our own custom TS compiler or related tools.

If there's a tool published to npm that can be wired into the build, then the starlark shimming around that tool could potentially make sense in rules_nodejs. This is a better layering of the solution, since the problem can be reproduced outside of Bazel, a solution ought to apply there too.

**Comment by amybzhao** [comment]
> If there's a tool published to npm that can be wired into the build, then the starlark shimming around that tool could potentially make sense in rules_nodejs. This is a better layering of the solution, since the problem can be reproduced outside of Bazel, a solution ought to apply there too.

Gotcha, this makes sense! Thanks for the thoughtful reply!
