### ISSUE TITLE
Allow setting output_format in rollup_bundle

### ISSUE THREAD

**Issue by mattem** [bazelbuild/rules_nodejs#374]
To deploy some Typescript to AWS Lambda we use rollup to bundle to a common JS module. At the moment it's only possible to generate iife or UMD bundles which currently don't work with Lambda (for a number of reasons).

**Comment by appsforartists** [comment]
From what I understand of Bazel, formatting is pull-based.  That is, rather than specifying `output_format` in `rollup_bundle`, whatever depends on `rollup_bundle` will ask it for the format it needs.  This is why the current `rollup_bundle` has targets like  `.es6.js`.

I would also like the ability to have a browser-compatible ESM/ES6 target.  I want to be able to write this code:

```typescript
// types.ts
export type ReturnsBoolean: () => boolean;

// yup.ts
import { ReturnsBoolean } from './types';
export const yup: ReturnsBoolean = () => true;

// nope.ts
import { ReturnsBoolean } from './types';
export const nope: ReturnsBoolean = () => false;

// index.ts
export { yup } from './yup';
export { nope } from './nope';
```

and be able to pull this bundle from Rollup:

```typescript
// bundle.js
export const yup = () => true
export const nope = () => false;
```

Seems like minification should be a separate concern (and a separate rule), but I'm not the Bazel expert.  @alexeagle is though.

**Comment by alexeagle** [comment]
@appsforartists is right.

Think of it this way: under most build tools, you can request that it builds one of the targets you've specified, and only those.
But under Bazel, a specified target can expand to multiple targets. That means that we have the choice of putting configuration into attributes on the rule, or requesting a different output from the rule.
Generally we prefer the second one because it improves usability. For one thing, if you need to generate multiple output formats, you don't need to have parallel build rules repeating the same things. The principle here is that BUILD files just describe your inputs and their dependency structure, not what to do.

Okay, that said, it so happens that the `rollup_bundle` rule already can produce CJS outputs, but only in code-splitting mode (when `additional_entry_points` is non-empty)
https://github.com/bazelbuild/rules_nodejs/blob/3c109ff7b1926e5497d59ba26833ded57a50c71c/internal/rollup/rollup_bundle.bzl#L392
so the request here is just to yield an additional output in non-code-splitting mode that runs a similar action.

**Comment by appsforartists** [comment]
I've split off the ESM request into #454.
