### ISSUE TITLE
package.json local paths

### ISSUE THREAD

**Issue by camargo** [bazelbuild/rules_nodejs#376]
I have a `package.json` that is using [local paths](https://docs.npmjs.com/files/package.json#local-paths) to reference another local npm module:

```json
{
    "dependencies": {
        "some-lib": "file: ./some-lib"
    }
}
```

I am using the [npm_install](https://bazelbuild.github.io/rules_nodejs/npm_install/npm_install.html#npm_install) rule and letting Bazel manage my npm dependencies. So in my [nodejs_binary](https://bazelbuild.github.io/rules_nodejs/node/node.html#nodejs_binary) I am doing `@npm/some-lib`. I consistently get this error when I try to build or run with Bazel:

```
npm ERR! Could not install from "some-lib" as it does not contain a package.json file.
```

`some-lib` does have a `package.json` but the `npm_install` rule can't seem to find it. Should I be able to use `package.json` local paths here? 

Thanks!

**Comment by mattem** [comment]
Is this a package.json that you control? Could you instead setup a source dependency on 'some-lib', eg:

```
rule(
    name = "foo",
    deps = ["//workspace/path/to/some_lib"],
)
```

**Comment by camargo** [comment]
I could but I'd like it to work normally with the `package.json` local path and the `@npm` namespace.

**Comment by gregmagolan** [comment]
@camargo `npm install` will be run in the bazel output_base folder so `some-lib` is not found in that location when it runs. The folder it runs in is `$(bazel info output_base)/external/rule_name`.

You can add files to the external repository that `npm install` run in with the `data` attribute. For example:

```
    yarn_install(
        name = "npm",
        package_json = "//:package.json",
        yarn_lock = "//:yarn.lock",
        data = [
        	"//:some-lib/package.json",
        	"//:some-lib/index.js",
        	...
        ],
    )
```

`glob()` doesn't work in this context so you have to list all the files out individually. `data` is an attribute of both `yarn_install` and `npm_install`.

**Comment by tristanz** [comment]
@gregmagolan Thanks for your explanation.   I am still having some difficulties though:

1.  My packages are not subfolders, they are referenced like `file:../../libs/some-lib`.  If I add `//:/libs/some-lib/package.json` bazel looks for `output_base/libs/some-lib` which does not exist since the library is placed at `output_base/external/rule_name/libs/some-lib`.   I can change the `package.json` file but that breaks a normal `yarn install`.

2. Listing all the data files is not feasible as there are thousands of files in these shared libraries.  

Do you have any advice here for good workarounds or suggestions on contributions that would be welcome?
