### ISSUE TITLE
Let user specify any version of node/npm/yarn

### ISSUE THREAD

**Issue by fortuna** [bazelbuild/rules_nodejs#4]
`rules_nodejs` forces Node.js v6. However, I'd like to use v8.
It would be great to have a way to specify which version I'm using.

**Comment by alexeagle** [comment]
I think we ought to support LTS versions of node - that means according to the schedule we should do it next month. https://github.com/nodejs/LTS

**Comment by kamalmarhubi** [comment]
I'd strongly advocate for making the version user specified. We've had serious issues with even minor version bumps, and would need to be able to choose the node version we use.

**Comment by alexeagle** [comment]
Fair enough. The only hard part I see is that I need a URL to fetch node from, and it's platform dependent, plus I have manually mirrored the current version to our CDN
https://github.com/bazelbuild/rules_nodejs/blob/master/internal/node_install.bzl#L29
So I'm not sure how the user would express this dependency. Maybe it's sufficient just to give the choice of major versions (6,7,8,9).

Also I have to pick which node versions these rules are tested against. And we want rules to be portable, so if you write a node program requiring 8, then all users must upgrade. Of course that problem exists without Bazel involved.

**Comment by kamalmarhubi** [comment]
For ease of use, the current setup is great. If adding flexibility, major version is not enough for us. For example, a patch upgrade from 4.8.2 to 4.8.4 caused segfaults in production for one of our services because of issues with a native module at that version. So it's important to be able to hold back certain `nodejs_binary` targets.

I was reading about [platforms](https://docs.google.com/document/d/1-G-VPRLEj9VyfC6VrQBiR8To-dZjnBSQS66Y4nargGM/edit?ts=57df9619) earlier, and it seems that might be the right way to go about this. Users could define toolchains like `node_6.11.3` and so on, or something like that? I haven't really understood the whole thing that well, and definitely haven't understood how toolchain resolution works.

As an intermediate that requires less fussing around with new concepts, the `nodejs_binary` rule could take a label to specify the nodejs executable to run. This lets users have very fine control where needed. Thoughts?

**Comment by alexeagle** [comment]
@kamalmarhubi I agree you need the ability to get any specific version. I'll look into platforms, but the simple answer is to change the `node_repositories` rule to allow you to pass a label for the the node (for each OS). You don't want it on `nodejs_binary` because then you could have different node version for different binaries in the same repo, which I think is a bad idea.

In addition to allowing you to specify any version, I just saw that Node 8 is now LTS so we should upgrade the default version that ships with the rules.

**Comment by Globegitter** [comment]
rules_go also allows to swap out the version of the go sdk, might be worth synchronising with how it is done there.

**Comment by alexeagle** [comment]
Fixed in https://github.com/bazelbuild/rules_nodejs/pull/183
