### ISSUE TITLE
Feature Request: Support patch in npm_install/yarn_install

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_nodejs#446]
There are cases, where we might need to inject additional build targets to the generated fine-grind build files. For instance, it would be convenient to have a `sass_library` target for sass files in an npm package.

As generating such rules for random files (without the help from package.json) is hard, IMHO we can support applying patches for the generated repository -- like http_archive, git_repository and rules_go do.

**Comment by alexeagle** [comment]
Yes, @gregmagolan and I discussed something similar. However it would be tricky to express the patch since there are many BUILD files created. I think you'll also have problems where a given npm package is installed with multiple versions - which BUILD files would be patched?

What is the severity here? I believe the workaround is simply to have the `sass_library` rule appear somewhere else in your own workspace. Could you explain why the workaround doesn't satisfy your needs?

**Comment by ashi009** [comment]
I've thought about doing that in my workspace, however the challenge here
is that the build rule will no longer match the import statement used in
the sass file. Which makes it more likely to create multiple workspace
target instead of having a shared one.

We used to use this workaround for using bazel query proto_library in go
before bazel supports patch, and the outcome is not pleasant.
Alex Eagle <notifications@github.com>于2018年12月5日 周三上午3:34写道：

**Comment by ashi009** [comment]
The approach I'm using right now is to use [patch-package](https://www.npmjs.com/package/patch-package) and include patches in the `data` attribute on `yarn_install`.

**Comment by alexeagle** [comment]
That sounds great, thanks for reporting back. since these are just npm packages, I agree we should use the standard npm ecosystem tooling to patch them - there shouldn't be anything bazel-specific about doing it.
