### ISSUE TITLE
Monorepo: is it possible to read dependencies from package.json?

### ISSUE THREAD

**Issue by spion** [bazelbuild/rules_nodejs#563]
I read through the docs but I couldn't figure out how to set up bazel for a classic lerna / yarn monorepo. Specifically, I can't figure out if its possible to read the dependencies for a bazel rule from another file i.e. `package.json`

What I like is to avoid duplication of specifying the dependencies twice, once in package.json for npm/yarn publishing and consumption/installation by other users, and once in Bazel for building via TypeScript in the right order.

Ideally I would have deps be generated from reading the [toplevel package.json `workspaces` entry](https://yarnpkg.com/lang/en/docs/workspaces/) globs, filtered through the individual package's own dependencies and devDependencies as specified in package.json

**Comment by alexeagle** [comment]
You're right, the deps are repeated right now.
In google, we don't use `package.json` files at all, so we accidentally brought that idiom with us. I think the best thing is for you to write `package.json` files in each package, and something like Gazelle generates BUILD files so that Bazel understands the package too.

**Comment by gregmagolan** [comment]
No longer in scope for rules_nodejs
