### ISSUE TITLE
Find a way to test ES2015 bundles in node

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#593]
As we change to support "differential loading", we produce ES Module bundles from rollup_bundle and other tools.

So far our strategy for testing was just to require() these bundles in node and assert on their side effects. But node doesn't understand `import` statements.

Maybe we need a browser test for these? Or at least some headless browser

**Comment by Toxicable** [comment]
If you write them as .mjs files and enable esm modules in nodejs you can import them
https://nodejs.org/api/esm.html

**Comment by alexeagle** [comment]
Thanks for the pointer, that's probably right.

Right now that causes a separate problem, which is that we currently use typescript to down-level the es2015 output, and it refuses to read a `.mjs` input with `--allowJs` flag. I started looking into using Babel instead, but that was an even bigger deal. I should pick up #235 to see if that solves it.

**Comment by jmaher409** [comment]
@alexeagle I've been playing around with trying to get es2015 modules working myself but am hitting some snags. Have you looked into this library https://www.npmjs.com/package/esm ? It seems like it should provide what is needed but I was struggling a bit getting it to work with the jasmine_node_test rule as I am new to bazel :).

**Comment by alexeagle** [comment]
note: following 56f03edb06b34b2d738132a6907b5413bb1b5559 we can pass 
` templated_args = ["--node_options=--experimental-modules"],`
to `//internal/e2e/rollup_code_splitting:test`
which might be a partial answer

**Comment by jmaher409** [comment]
@alexeagle 
Yes that looks like it would help a lot. I'm current using a hacked version of jasmine_node_test to play with this. The following code let me use the esm library to run tests against arbitrary combinations of es6 and cjs
```
templated_args = templated_args + ["--node_options=--require=esm"]
```

It looks like the commit you linked above will allow me to pass in templated_args instead of overriding the rule. 

I played around with using the experimental modules option as well but it has some additional requirements that seemed to make it a bit more complicated. I think I would need to either generate .mjs files or fake a package.json within the runfiles that contains `"type": "module"`. However, this may still be the better solution long term as it requires no external dependencies.
