### ISSUE TITLE
Unable to patch @npm_bazel_XYZ rules

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/rules_nodejs#694]
# 🚀 feature request

### Relevant Rules

`build_bazel_rules_typescript` and `build_bazel_rules_karma` become internal (non-public). Public starlark rules are exposed by `npm_bazel_typescript` and `npm_bazel_karma`, which indeed includes source codes from the `build_bazel_rules_***` rules. As I understand, the `build_bazel_rules_***` rules are no longer enough. They have to be used with the new `npm_bazel_***` rules to be complete. Is my understanding correct and complete? Open to comments.

The new `npm_bazel_***` rules are released as `npm` packages, i.e., `@bazel/typescript` and `@bazel/karma`. Is there another way for me to get the `npm_bazel_***` rules in source format?

The problem I have is that I need to occasionally patch some rules. For example, to allow `jasmine_node_test` to take a parameter to recognize a `jasmine.config` file. But with the new `npm_bazel_***` rules, I have not found a good way to patch the rules, if any at all.

RIght now, I just downloaded the `@bazel/typescript` package (as an example) and created a private git repo for it. And then using `native.local_repository` on it. This way, I can patch it the way I want. Clearly this is not optimal.

Help is wanted. Many thanks.

### Description

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by alexeagle** [comment]
The difference isn't really public/private, it's that our distributions have a simpler dependency structure than our sources.

The easy way to patch would be a postinstall script in your package.json that edits the files in `node_modules/@bazel/...` - this works fine under Bazel.

A bigger change would be to have a dependency on the sources of these rules rather than our published distribution, but this will be a lot more churn for you, since we have might have transitive dependencies like rules_go and you'd have to have matching versions for those in your `WORKSPACE`.

How did you patch the rules before? By forking the repo and maintaining a branch with the changes?
If so, what we really need is a github repo containing build snapshots matching what we publish to NPM, then you could fork that and install with a `github:` url in the package.json

**Comment by qzmfranklin** [comment]
Thanks @alexeagle for the information!

Per 'how we patched the rules before': We did exactly what you described: fork and maintain a separate branch, and then pull from upstream from time to time.

I would indeed appreciate a separate repo or branch from angular or bazel to maintain the build artifacts to allow us to patch the rules more easily using a `github:` url in package.json

**Comment by qzmfranklin** [comment]
We already hard copied the npm package and did the modifications needed. Happy for now.
