### ISSUE TITLE
Add renovate update bot to this repository

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#716]
It would be really helpful to have renovate handle dependency updates in this repository.

https://github.com/renovatebot/renovate.

This is working out really well in the `angular-bazel-example` repo using this config. https://github.com/angular/angular-bazel-example/blob/master/renovate.json

**Comment by alexeagle** [comment]
It's already here!

https://github.com/bazelbuild/rules_nodejs/blob/master/renovate.json

This is currently just sending PRs to update the rules_typescript commit hash, so that changes to tsc_wrapped, ts_auto_deps, and so on get released with @bazel/typescript

You can add more things for it to update!

**Comment by gregmagolan** [comment]
🤦‍♂️
