### ISSUE TITLE
npm_install uses "/usr/bin/env node" instead of the node managed by bazel

### ISSUE THREAD

**Issue by sconover** [bazelbuild/rules_nodejs#77]
fyi - this is evident on my build host where there's no node available in the environment. The build fails with:

`no such package '@npm_json//': npm_install failed: (/usr/bin/env: 'node': No such file or directory`

I note that `external/nodejs/bin/npm` starts with `#!/usr/bin/env node`, which, if I understand bazel philosophy correctly, seems like a problem.

**Comment by alexeagle** [comment]
correct, we should not call `npm` directly, we should do the equivalent of `external/nodejs/bin/node path/to/npm.js`

**Comment by aproxs** [comment]
FYI, seems that this will be a bigger problem once people starts picking up the latest versions of nodejs.
Node released 9.3.0 and the version is now available in the different package managers (homebrew in my case).

Because bazel is using my non-hermetic node, bazel is trying to use this versions:
 - node: 9.3.0 (from homebrew)
 - npm: 5.5.1 (from rules_nodejs)

It seems that this specific combo is incompatible and I get the following error:
'''
1 warn npm npm does not support Node.js v9.3.0    
2 warn npm You should probably upgrade to a newer version of node as we    
3 warn npm can't make any promises that npm will work with this version.    
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.   
...
7 info using npm@5.5.1    
8 info using node@v9.3.0 
"""

I think this is the related issue from nodejs
nodejs/node#16649

**Comment by alexeagle** [comment]
Thanks for pointing this out, @aproxs .
I will try to get to it this week.

**Comment by adamyi** [comment]
Any updates on this?

**Comment by alexeagle** [comment]
Nope, sorry, ran out of time. We'll put some issues on the sprint plan
tomorrow.

**Comment by alexeagle** [comment]
Handing to Greg, this goes along with refactoring he's doing in `npm_install`

**Comment by gregmagolan** [comment]
PR posted that fixes this #105
